const programSSM = {
  stage_1: {
    april_17: [
      {
        hour: '12:00 - 12:30',
        name: '',
        title: 'BESS: 10 puntos clave para instalar almacenamiento en las industrias',
        title_en: 'BESS: 10 key points to install storage in industries',
        speakers: 'Ricardo Nava',
        description: '',
        description_en : '',
        position: 'Director de Instalaciones e Ingeniería',
        position_en: 'Director of Facilities and Engineering',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '12:45 – 13:15',
        name: '',
        title: 'Almacenamiento de Energía: Aplicaciones reales, financiamiento y nuevas oportunidades',
        title_en: 'Energy Storage: Real-world applications, financing and new opportunities',
        speakers: 'Alejandro Fajer Botaya',
        description: 'Explora las aplicaciones prácticas, opciones de financiamiento y nuevas oportunidades en el campo del almacenamiento de energía. Descubre cómo esta tecnología está transformando diversos sectores y cómo puedes capitalizar estas tendencias en tu propio contexto. Únete a nosotros para una sesión informativa que te ayudará a entender el potencial y las posibilidades del almacenamiento de energía en el mundo actual.',
        description_en : 'Explore practical applications, financing options and new opportunities in the field of energy storage. Discover how this technology is transforming various sectors and how you can capitalize on these trends in your own context. Join us for an informative session that will help you understand the potential and possibilities of energy storage in today\'s world.',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '13:30 –14:00',
        name: '',
        title: 'BATTERY DEPOT',
        title_en: 'BATTERY DEPOT',
        speakers: '',
        description: '',
        description_en : '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '14:15 –14:45',
        name: 'APsystems',
        title: 'Nuevas tecnologías de APsystems para el mercado Latinoamericano',
        title_en: 'New APsystems technologies for the Latin American market',
        speakers: 'Gustavo Marín',
        description: 'APsystems presenta lo nuevo en tecnología para microinversores MLPE y la reciente solución de almacenamiento de energía. La tecnología Apsystems avanza continuamente para ofrecer los equipos más competentes en el mercado de Latinoamérica adaptándose a lo actual y futuro. Traemos para ti lo más reciente en microinversores bifásicos y trifásicos, y la solución para almacenamiento de energía el APstorage que viene acompañado de su Power Conversion Systems (PCS) y el Auto-transformador de fase dividida.',
        description_en: 'APsystems presents the new technology for MLPE microinverters and the recent energy storage solution. APsystems technology continually advances to offer the most competent equipment in the Latin American market, adapting to current and future advances. We bring you the latest technology in two-phase and three-phase microinverters, and the APstorage energy storage solution that comes with its Power Conversion Systems (PCS) and the split-phase Transformer.',
        position: 'Branch Manager en LATAM APsystems',
        position_en: 'Branch Manager at LATAM APsystems',
        avatars: ['/speakers/gustavo_marin.webp', '', ''],
        id: [2]
      },
      {
        hour: '15:00 –16:00',
        name: '',
        title: 'BREAK',
        title_en: 'BREAK',
        speakers: '',
        description: '',
        description_en : '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '16:00 –16:30',
        name: '',
        title: 'Soluciones residenciales y comerciales híbridas con respaldo de energía',
        title_en: 'Hybrid residential and commercial solutions with energy back-up',
        speakers: 'Erick Möller',
        description: 'Explora cómo las innovadoras soluciones de respaldo de energía de Sol-Ark están impulsando la eficiencia y la sostenibilidad en entornos residenciales y comerciales.',
        description_en : 'Explore how Sol-Ark\'s innovative power backup solutions are driving efficiency and sustainability in residential and commercial environments.',
        position: 'Gerente Regional Ventas LATAM, at Sol-Ark',
        position_en: 'Regional Sales Manager LATAM, at Sol-Ark',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '17:30 - 18:00',
        name: '',
        title: 'HUAWEI',
        title_en: 'HUAWEI',
        speakers: '',
        description: '',
        description_en : '',
        avatar: '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      },
    ],
    april_18: [
      {
        hour: '12:00 - 12:30',
        name: '',
        title: 'LONGI',
        title_en: 'LONGI',
        speakers: '',
        description: '',
        description_en : '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '12:45 –13:15',
        name: '',
        title: 'KRANNICH',
        title_en: 'KRANNICH',
        speakers: '',
        description: '',
        description_en : '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '13:30 –14:00',
        name: 'S-5!',
        title: 'Caso de estudio: Comportamiento de un proyecto FV en techo metálico engargolado frente a huracán categoría 5 en Acapulco',
        title_en: 'Case study: Performance of a PV project on a metal roof with a metal roof in the face of a category 5 hurricane in Acapulco, Mexico.',
        speakers: 'Alejandro Terán | Juan Carlos Fuentes ',
        description: 'Análisis de techos métalicos engargolados como plataforma para Energía FV y la importancia de la elección de un sistema de racking adecuado. Además, se estudiará el comportamiento de un proyecto FV frente a un Huracán con vientos de más de 200 km/h instalado con las piezas de fijación directa sin rieles de S-5!',
        description_en: 'Analysis of metal roofs as a platform for PV energy and the importance of choosing a suitable racking system. In addition, the behavior of a PV project against a Hurricane with winds of more than 200 km/h installed with S-5!',
        position: 'Director de construcción, en Energía Real | Director de Ventas para Latinoamérica & Europa, en S-5!',
        position_en: 'Director of Construction, at Energía Real | Sales Director for Latin America & Europe at S-5!',
        avatars: ['/speakers/alejandro_teran.webp', '/speakers/juan_carlos_fuentes.webp', ''],
        id: [1, 3]
      },
      {
        hour: '14:15 –14:45',
        name: '',
        title: 'Equipos para el diagnóstico y evaluación de paneles y sistemas fotovoltaicos.',
        title_en: 'Equipment for the diagnosis and evaluation of photovoltaic panels and systems.',
        speakers: 'Iván Zavala Vera',
        description: 'Diagnóstico y evaluación de eficiencia de Sistemas Fotovoltaicos por medio de Equipos Trazadores de Curvas IV, de acuerdo con las normativas y requerimientos para la instalación y mantenimiento preventivo de paneles solares.',
        description_en: 'Diagnosis and evaluation of efficiency of Photovoltaic Systems through IV Curve Tracing Equipment, in accordance with the regulations and requirements for the installation and preventive maintenance of solar panels.',
        position: '',
        position_en: '',
        avatars: ['/speakers/ivan_zavala_vera.webp', '', ''],
        id: [5]
      },
      {
        hour: '15:00 –16:00',
        name: '',
        title: 'BREAK',
        title_en: 'BREAK',
        avatar: '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]

      },
      {
        hour: '16:00 –16:30',
        name: '',
        title: 'Soluciones de Energy Storage con Victron Energy',
        title_en: 'Energy Storage Solutions with Victron Energy',
        speakers: 'David Gutiérreza',
        avatar: '',
        position: 'Country Manager México, de Victron Energy',
        position_en: 'Country Manager México, of Victron Energy',
        description: 'Conoce las oportunidades de negocio y alcance de los equipos de la marca holandesa número 1 en el mercado del Almacenamiento de Energía',
        description_en: 'Learn about the business opportunities and scope of the equipment of the number 1 Dutch brand in the Energy Storage market.',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '16:45 –17:15',
        name: '',
        title: 'ESS Y PPA; SOLAREVER',
        title_en: 'ESS Y PPA; SOLAREVER',
        speakers: 'Raul Romay | Mayela Cifuentes',
        avatar: '',
        position: '',
        position_en: '',
        description: 'Energía solar al alcance de tus manos: herramientas financieras para proyectos fotovoltaicos, además de explorar el futuro de la energía con sistemas de almacenamiento en México',
        description_en: 'Solar energy at your fingertips: Financial Tools for Photovoltaic projects, in addition to exploring the future of energy with storage systems in Mexico',
        avatars: ['', '/speakers/mayela_cinfuentes.webp', ''],
        id: [0,7,0]
      },
      {
        hour: '17:30 –18:00',
        name: '',
        title: 'AVAILABLE',
        title_en: 'AVAILABLE',
        avatar: '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      }
    ],
    april_19: [
      {
        hour: '12:00 - 12:30',
        name: '',
        title: 'BATTERY DEPOT',
        title_en: 'BATTERY DEPOT',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '12:45 –13:30',
        name: 'GRUNDFOS',
        title: 'Sistemas de Bombeo Solar Fotovoltaico: Una visión general y el papel de Grundfos en el sector',
        title_en: 'Photovoltaic Solar Pumping Systems: An overview and the role of Grundfos in the sector',
        speakers: 'José Adolfo Ortiz Martínez',
        description: 'Una de las aplicaciones más importantes de la energía solar fotovoltaica es sin duda alguna el bombeo de agua utilizando paneles solares, esto es conocido como Sistemas de Bombeo Solar. Este tipo de sistemas ha tenido un creciente interés, especialmente en países en vías de desarrollo, como producto de la transición energética que se vive a nivel mundial. En países como México, con una fuerte dependencia del sector primario, se tiene una ventaja competitiva para este tipo de sistemas, ya que resuelve muchos de los problemas operativos y de disponibilidad energética en los sitios productivos. Para explicar esto, los puntos clave que repasaremos en nuestra charla son:- El papel de Grundfos en el sector como pionero tecnológico a nivel mundial y actor clave en México.- Cómo colabora Grundfos a través del bombeo solar con los Objetivos de Desarrollo Sustentable a nivel mundial.- Explicación y evidencias de los usos más comunes de este tipo de sistemas en México.',
        description_en: 'One of the most important applications of photovoltaic solar energy is undoubtedly the pumping of water using solar panels, this is known as Solar Pumping Systems. This type of systems has had a growing interest, especially in developing countries, as a product of the energy transition that is being experienced worldwide. In countries like Mexico, with a strong dependence on the primary sector, there is a competitive advantage for this type of system, since it solves many of the operational and energy availability problems in productive sites. To explain this, the key points we will review in our talk are: - Grundfos\' role in the sector as a technological pioneer worldwide and key player in Mexico. - How Grundfos collaborates through solar pumping with the Sustainable Development Goals worldwide. - Explanation and evidence of the most common uses of this type of systems in Mexico.',
        position: '',
        position_en: '',
        avatars: ['/speakers/jose_adolfo.web', '', ''],
        id: [4]
      },
      {
        hour: '13:30 –14:00',
        name: '',
        title: 'La electromovilidad, una solución cero emisión',
        title_en: 'Electric mobility, a zero-emission solution',
        speakers:"Javier López ",
        description:"Un panorama de los desafíos y desarrollo de la industria de autos eléctricos en México. Los caminos que ha encontrado para competir en el mundo automotriz. ",
        description_en:"An overview of the challenges and development of the electric car industry in Mexico. The ways it has found to compete in the automotive world.",
        avatar: '',
        position: '',
        position_en: '',
        avatars: ['/speakers/javier_lopez.webp', '', ''],
        id: [8]
      },
      {
        hour: '14:15 –14:45',
        name: '',
        title: 'HUAWEI',
        title_en: 'HUAWEI',
        speakers: '',
        description: '',
        description_en : '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '15:00 –15:30',
        name: '',
        title: 'AVAILABLE',
        title_en: 'AVAILABLE',
        avatar: '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '15:45 - 16:30',
        name: '',
        title: 'CLAUSURA',
        title_en: 'CLAUSURA',
        avatar: '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      }
    ]
  },
  stage_2: {
    april_17: [
      {
        hour: '11:30 - 14:30',
        duration: '3 hrs.',
        name: '',
        title: 'IBESA 101 Taller de Almacenamiento: Navegando por el panorama de almacenamiento de energía en México: Liberando oportunidades y estrategias de monetización',
        title_en: 'IBESA 101 Storage Workshop: Navigating the Mexican Energy Storage Landscape: Unlocking Opportunities and Monetization Strategies',
        description: 'Sumérgete en un taller interactivo que desmitifica la evolución del mercado de almacenamiento de energía en México y sus regiones vecinas. Esta sesión está meticulosamente diseñada para atender a instaladores, desarrolladores, empresas de servicios públicos, proveedores de tecnología, formuladores de políticas y personas influyentes en el almacenamiento, tanto a nivel nacional como internacional. Los participantes profundizarán en una exploración integral de las perspectivas de almacenamiento de energía, tecnologías de vanguardia y la intrincada red de políticas y regulaciones. Adquiere los conocimientos de mercado respaldados por datos proporcionados por prestigiosas organizaciones de investigación, complementados con estudios de casos de la vida real de líderes de la industria. Este taller tiene como objetivo hacer que las propuestas de valor del almacenamiento de energía en los sectores residencial, comercial y de servicios públicos sean más tangibles y accesibles para todos los asistentes.',
        description_en: 'Dive into an interactive workshop that demystifies the evolving energy storage market in Mexico and its neighboring regions. This session is meticulously designed to cater to installers, developers, utilities, technology providers, policymakers, and pivotal storage influencers, both nationally and internationally. Participants will delve into a comprehensive exploration of energy storage prospects, cutting-edge technologies, and the intricate web of policies and regulations. Immerse yourself in data-backed market insights provided by esteemed research organizations, complemented by real-life case studies from industry leaders. This workshop aims to make the value propositions of energy storage in residential, commercial, and utility-scale sectors more tangible and accessible for all attendees.',
        speakers: 'Daniel Fuchs | Alejandro Fajer | Marcel Gómez Pecina | Erika Ramírez | Carlos Torres Almazán | Maximiliano Orduño | Santiago Torres | Gustavo Marín',
        position: 'Director de Atención al Cliente (CCO), International Battery & Energy Storage Alliance - IBESA | COO de Quartux México | Desarrollador de negocios energéticos, en ON. Energy | Analista Senior de Operaciones en Acclaim Energy México | Director General de EMS Latin America | Especialista de Producto, en Growatt | Socio Director de Pireos Power | Branch Manager LATAM at AP Systems ',
        position_en: 'Chief Customer Officer (CCO), International Battery & Energy Storage Alliance - IBESA | COO at Quartux México | Energy Business Developer at ON. Energy | Operations Sr. Analyst at Acclaim Energy México | Managing Director at EMS Latin America | Product Specialist, at Growatt | Managing Partner at Pireos Power | Branch Manager LATAM at APsystems',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '16:00 - 17:00',
        duration: '1 hrs.',
        name: '',
        title: 'REDMEREE',
        title_en: 'REDMEREE',
        speakers: '',
        description: 'Más información por confirmar',
        description_en: 'More information to be confirmed',
        avatar: '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      },
    ],
    april_18: [
      {
        hour: '11:30 - 14:30',
        duration: '3 hrs.',
        name: '',
        title: 'IBESA 201 Masterclass de Almacenamiento de Energía : Estrategias de Negocio Innovadoras, Tecnologías de Vanguardia y Sistemas Inteligentes',
        title_en: 'IBESA 201 Energy Storage Masterclass: Innovative Business Strategies, Cutting-edge Technologies, and Intelligent Systems',
        description: 'Eleve su experiencia en almacenamiento de energía con nuestro taller avanzado diseñado para el mercado mexicano. Presentamos "Dominio del almacenamiento de energía: estrategias comerciales innovadoras, tecnologías de vanguardia y sistemas inteligentes", diseñado exclusivamente para profesionales dedicados al sector del almacenamiento de energía. Este taller ofrece una comprensión integral de los últimos modelos comerciales, avances tecnológicos y el arte de crear soluciones de almacenamiento inteligentes. A través de estudios de casos inmersivos de la vida real y conocimientos de expertos de la industria, explorará el profundo impacto que tiene el almacenamiento de energía en la conservación del medio ambiente. Obtenga conocimientos invaluables sobre diversas configuraciones y operaciones de almacenamiento que contribuyen significativamente a los esfuerzos de descarbonización.',
        description_en: 'Elevate your expertise in energy storage with our advanced workshop tailored for the Mexican market. Introducing "Energy Storage Mastery: Innovative Business Strategies, Cutting-edge Technologies, and Intelligent Systems," designed exclusively for professionals engaged in the energy storage sector. This workshop offers a comprehensive understanding of the latest business models, technological advancements, and the art of crafting intelligent storage solutions. Through immersive real-life case studies and insights from industry experts, you\'ll explore the profound impact energy storage has on environmental conservation. Gain invaluable knowledge about diverse storage configurations and operations that contribute significantly to decarbonization efforts.',
        speakers: 'Daniel Fuchs | Marco V. Calderón Agoitia | Patricia Tatto | César Garma | Hector Núñez | Luis Antonio Hernandez García | Rogelio Nochebuena',
        avatar: '',
        position: 'Director de Atención al Cliente (CCO), International Battery & Energy Storage Alliance - IBESA | Socio Director de Cosmo Consulting | Vicepresidenta de ATA renewables America | Director de Estrategia de Transición Energética de Saving With Energy México | Jefe de Ventas para Norteamérica en Sungrow Power Supply | Director General en Battery DepotMx | Director de SEBA - Servicios Ambientales de Baja California',
        position_en: 'Chief Customer Officer (CCO), International Battery & Energy Storage Alliance - IBESA | Managing Partner at Cosmo Consulting | Vice President at ATA renewables America | Director Energy Transition Strategy from Saving With Energy México | North Latam Head of Sales at Sungrow Power Supply | General Manager at Battery DepotMx | Principal at SEBA - Baja California Environmental Services',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '16:00 - 17:00',
        duration: '1 hr.',
        name: '',
        title: 'ASOCIACIÓN MEXICANA DE HIDRÓGENO: Hidrogeno Verde',
        title_en: 'ASOCIACIÓN MEXICANA DE HIDRÓGENO: Green Hydrogen',
        speakers: '',
        description: 'Más información por confirmar',
        description_en: 'More information to be confirmed',
        avatar: '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      },
    ],
    april_19: [
      {
        hour: '12:00 - 13:00',
        duration: '1 hr',
        name: '',
        title: 'ASOCIACIÓN MEXICANA DE HIDRÓGENO: Hidrogeno Verde',
        title_en: 'ASOCIACIÓN MEXICANA DE HIDRÓGENO: Green Hydrogen',
        speakers: '',
        description: 'Más información por confirmar',
        description_en: 'More information to be confirmed',
        avatar: '',
        position: '',
        position_en: '', 
        avatars: ['', '', ''],
        id: [0]
      },
    ]
  },
  stage_3: {
    april_17: [
      {
        hour: '11:00 -12:00',
        name: '',
        title: 'Seguridad y salud al enfrentar incendios en los que se involucran baterías de Ion-Litio',
        title_en: 'Security and health when dealing with fires involving Lithium-Ion batteries',
        description: '',
        description_en : '',
        speakers: 'José de Jesús Martínez Garza',
        avatar: '',
        position: 'Director de IAAR',
        position_en: 'Director of IAAR',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '12:00 - 13:00',
        name: '',
        title: 'SEI 1',
        title_en: 'SEI 1',
        description: '',
        description_en : '',
        speakers: '',
        avatar: '',
        position: 'Instructor de SEI',
        position_en: 'SEI Instructor',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '13:00 - 14:00',
        name: '',
        title: 'Actualización de estándares de competencia para la industria fotovoltaica',
        title_en: 'Updating of competency standards for the photovoltaic industry',
        description: '',
        description_en : '',
        speakers: 'Marco Guzmán',
        avatar: '',
        position: 'Coordinador Operativo Comité de Gestión de Competencias de Eficiencia Energética y Energía Renovable',
        position_en: 'Operational Coordinator Energy Efficiency and Renewable Energy Competency Management Committee',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '16:00 - 17:00',
        name: '',
        title: 'SEI 2',
        title_en: 'SEI 2',
        description: '',
        description_en : '',
        speakers: '',
        avatar: '',
        position: 'Instructor de SEI',
        position_en: 'SEI Instructor',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '17:00 - 18:00',
        name: '',
        title: '¿Son suficientes las normas que regulan el sector fotovoltaico para asegurar la calidad y la seguridad de las instalaciones?',
        title_en: 'Are the regulations governing the photovoltaic sector sufficient to ensure the quality and safety of installations?',
        description: '',
        description_en : '',
        speakers: 'Leonardo Velasco Ochoa',
        avatar: '',
        position: 'InspectaPV',
        position_en: 'InspectaPV',
        avatars: ['', '', ''],
        id: [0]
      },
    ],
    april_18: [
      {
        hour: '11:00 - 12:00',
        name: '',
        title: 'Negocios solares rentables inclusivos',
        title_en: 'Inclusive and profitable solar businesses',
        description: '',
        description_en : '',
        speakers: 'Aideé Zamora',
        avatar: '',
        position: 'Redmeré',
        position_en: 'Redmeré',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '12:00 - 13:00',
        name: '',
        title: '¿Cómo lograr éxito y eficiencia en los proyectos solares en piso?',
        title_en: 'How to achieve success and efficiency in ground-mounted solar projects?',
        description: '',
        description_en : '',
        speakers: 'Alfonso Germán Jalil',
        avatar: '',
        position: 'Strip Stell',
        position_en: 'Strip Stell',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '13:00 - 14:00',
        name: '',
        title: 'Soluciones de almacenamiento y cero inyección',
        title_en: 'Storage and zero-injection solutions',
        description: '',
        description_en : '',
        speakers: 'Sergio Rodríguez Solis',
        avatar: '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '16:00 - 17:00',
        name: '',
        title: 'El modelo de Abasto Aislado',
        title_en: 'The Isolated Supply model',
        description: '',
        description_en : '',
        speakers: 'Casiopea Ramírez',
        avatar: '',
        position: 'Socia de Fresh Energy Consulting',
        position_en: 'Partner of Fresh Energy Consulting',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '17:00 - 18:00',
        name: '',
        title: 'Requerimientos técnicos en la regulación, para la GD',
        title_en: 'Technical requirements in regulation, for DG',
        description: '',
        description_en : '',
        speakers: 'Gilberto Sánchez',
        avatar: '',
        position: 'Secretario Legislativo en la Asociación Nacional de Energía Solar (ANES)',
        position_en: 'National Solar Energy Association Legislative Secretary',
        avatars: ['', '', ''],
        id: [0]
      },
    ],
    april_19: [
      {
        hour: '11:00 - 12:00',
        name: '',
        title: 'Tecnologías para protección por falla de arco en sistemas fotovoltaicos',
        title_en: 'Technologies for arc-fault protection in photovoltaic systems',
        description: '',
        description_en : '',
        speakers: 'Luciano Ángel Estévez | Estevez Books',
        avatar: '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '13:00 - 14:00',
        name: '',
        title: 'La importancia de los servicios de la UVIE durante el proceso de diseño e instalación del SFV',
        title_en: 'The importance of UVIE\'s services during the design and installation process of the SFV',
        description: '',
        description_en : '',
        speakers: 'Víctor Hugo Rangel',
        avatar: '',
        position: '',
        position_en: '',
        avatars: ['', '', ''],
        id: [0]
      },
      {
        hour: '16:00 - 17:00',
        name: '',
        title: 'Financiamiento y PPA para sistemas fotovoltaicos y de almacenamiento (BESS)',
        title_en: 'Financing and PPAs for photovoltaic and storage systems (BESS)',
        description: '',
        description_en : '',
        speakers: 'Chantal Sanabria',
        avatar: '',
        position: 'Energía Real',
        position_en: 'Energía Real',
        avatars: ['', '', ''],
        id: [0]
      },
    ]
  }
}

const conferencesSSM = {
  day_1: [
    {
      type: 'Conferencia',
      type_en: 'Conference',
      duration: '45 min',
      timetable: '10:00 - 10:45',
      title: 'Nearshoring, Inversión Extranjera Directa y Energía Limpia',
      title_en: 'Nearshoring, Foreign Direct Investment and Clean Energy',
      subject: 'Políticas Energéticas',
      subject_en: 'Energy Policy',
      description: '',
      description_en: '',
      peakers: 'Jesús Carrillo',
      position: 'Director de Economía del Instituto Mexicano para la Competitvidad A.C. (IMCO)',
      position_en: 'Director of Economics at Instituto Mexicano para la Competitvidad A.C. (IMCO)',
      avatars: ['/speakers/jesus_carrillo.webp', '', ''],
      id: [7]
    },
    {
      type: 'Conferencia',
      type_en: 'Conferencia',
      duration: '45 min',
      timetable: '10:45 - 11:30',
      title: 'La visión subnacional de la transición energética: aprendizajes y desafíos',
      title_en: 'The subnational vision of energy transition: lessons learned and challenge',
      subject: 'Generación Fotovoltaica Distribuida',
      subject_en: 'Distributed Photovoltaic Generation',
      description: '',
      description_en: '',
      peakers: ' Ana Lilia Moreno',
      position: 'Coordinadora e investigadora del Programa de Regulación y Competencia Económica en México Evalúa',
      position_en: 'Coordinator and researcher of the Regulation and Economic Competition Program at México Evalúa',
      avatars: ['/speakers/ana_lilia.webp', '', ''],
      id: [12]
    },
    {
      type: 'Panel',
      type_en: 'Panel',
      duration: '45 min',
      timetable: '11:30 - 12:15',
      title: 'Importancia de la certificación en el sector solar',
      title_en: 'Importance of certification in the solar sector',
      subject: 'Generación Fotovoltaica Distribuida',
      subject_en: 'Distributed Photovoltaic Generation',
      description: '',
      description_en: '',
      peakers: 'Dra. Carolin Antoni |  Celeste Morales | Eduardo Gómez',
      position: 'Gerente del departamento de desarrollo sostenible de CAMEXA | IER-UNAM | Director Comercial de LATAM Maxeon Solar Technologies ',
      position_en: 'Manager of CAMEXA\'s Sustainable Development Department | IER-UNAM |Commercial Director of LATAM Maxeon Solar Technologies',
      avatars: ['/speakers/carolin_antoni.webp', '/speakers/celeste-morales.webp', '/speakers/eduardo_gomez.webp'],
      id: [11, 14, 6]
    },
    {
      type: 'Conferencia',
      type_en: 'Conference',
      duration: '45 min',
      timetable: '12:45 - 13:30',
      title: 'Asegurar la calidad en centrales solares en Generación Distribuida',
      title_en: 'Quality assurance in solar power plants in Distributed Generation',
      subject: 'Generación Fotovoltaica Distribuida',
      subject_en: 'Distributed PV',
      description: '',
      description_en: '',
      peakers: 'Ana Karina Torres | Leonardo Velasco | Andrew Kiefer McNeil',
      position: 'DYPESA |  Inspecta PV | CEA',
      position_en: '',
      avatars: ['/speakers/ana_karina_torres.webp', '/speakers/leonardo_velasco.webp', '/speakers/andrew_kiefer_v2.webp'],
      id: [19, 22 , 20]
    },
    {
      type: 'Panel',
      type_en: 'Panel',
      duration: '45 min',
      timetable: '13:30 - 14:15',
      title: 'Acceso a energía renovable a través del Abasto Aislado',
      title_en: 'Access to renewable energy through Isolated Supply',
      subject: 'Escala de Servicio Público',
      subject_en: 'Public Service Scale',
      description: '',
      description_en: '',
      peakers: 'Angélica Soto | Humberto Alarcón | Luis Gerardo Sánchez Stone',
      position: 'Directora General de Nx Buena Energía | SUNECO | Director General de ErgoSolar',
      position_en: 'Managing Director of Nx Buena Energía  | SUNECO | General Manager of ErgoSolar',
      avatars: ['/speakers/angelica_soto.webp', '/speakers/luis_sanchez.webp', ''],
      id: [1, 4]
    },
  ],
  day_2: [
    {
      type: 'Conferencia',
      type_en: 'Conference',
      duration: '45 min',
      timetable: '10:00 - 10:45',
      title: 'Principales desafíos del sector eléctrico de México',
      title_en: 'Main challenges of Mexico\'s electricity sector',
      subject: 'A Escala de Servicio Público',
      subject_en: 'Public Service Scale',
      description: '',
      description_en: '',
      peakers: ' Mario S. DePillis Jr. ',
      position: 'Miembro de Cigré y de la American Economic Association',
      position_en: 'Member of Cigré and the American Economic Association',
      avatars: ['/speakers/mario_pillis.webp', '', ''],
      id: [3]
    },
    {
      type: '',
      type_en: '',
      duration: '45 min',
      timetable: '10:45 - 11:30',
      title: 'Evolución de la Regulación para Generación Distribuida hacia 2030',
      title_en: 'Evolution of the regulation for Distributed Generation towards 2030 ',
      subject: 'Generación Fotovoltaica Distribuida',
      subject_en: 'Distributed PV',
      description: '',
      description_en: '',
      peakers: 'Ángel Mejía Santiago | Gilberto Sánchez Nogueira | Casiopea Ramírez Melgar',
      position: ' Presidente de la Asociación Mexicana de la Industria Fotovoltaica (AMIF)  | Legislative Secretary of the National Association of Solar Energy (ANES) | Socia de Fresh Energy',
      position_en: 'President of the Mexican Photovoltaic Industry Association (AMIF) | Legislative Secretary of the National Association of Solar Energy (ANES)| Partner of Fresh Energy Consulting (Fresh Energy) ',
      avatars: ['/speakers/angel_mejia.webp', '/speakers/gilberto_sanchez.webp', '/speakers/casiopea_ramirez.webp'],
      id: [17, 21, 18 ]
    },
    {
      type: 'DUO',
      type_en: 'DUO',
      duration: '45 min',
      timetable: '11:30 - 12:15',
      title: 'Propuesta de ruta emisiones netas cero para México',
      title_en: 'Proposed net zero emissions pathway for Mexico',
      subject: 'Políticas Energéticas',
      subject_en: 'Energy Policies',
      description: '',
      description_en: '',
      peakers: 'Jorge Villarreal Padilla | Luisa Sierra Brozon',
      position: 'Director de Política Climática, en ICM | Directora del Programa de Energía dentro de la Iniciativa Climática de México (ICM)',
      position_en: 'Director of Climate Policy, MSI | Director of the Energy Program within the Mexico Climate Initiative (MSI)',
      avatars: ['/speakers/jorge_villarreal.webp', '/speakers/luisa_sierra.webp', ''],
      id: [8, 9]
    },
    {
      type: 'Panel',
      type_en: 'Panel',
      duration: '45 min',
      timetable: '12:45 - 13:30',
      title: 'Equidad de género en el sector energético',
      title_en: 'Gender equity in the energy sector',
      subject: 'Generación Fotovoltaica Distribuida',
      subject_en: 'Distributed Photovoltaic Generation',
      description: '',
      description_en: '',
      peakers: 'Carolin Antoni',
      position: 'CAMEXA',
      position_en: 'CAMEXA',
      avatars: ['/speakers/carolin_antoni.webp', '', ''],
      id: [11]
    },
    {
      type: 'Panel',
      type_en: 'Panel',
      duration: '45 min',
      timetable: '13:30 - 14:15',
      title: 'Almacenamiento de energía eléctrica detrás del medidor',
      title_en: 'Electrical energy storage behind the meter',
      subject: 'Almacenamiento',
      subject_en: 'Storage',
      description: '',
      description_en: '',
      peakers: 'Valeria Amezcua Santillán | Enrique Garduño | Ena Gutiérrez',
      position: 'Presidenta de Red Agrovoltaica Mexicana | CEO Skysence | ENLIGHT ',
      position_en: 'President of the Mexican Agrovoltaic Network | CEO Skysence | ENLIGHT',
      avatars: ['/speakers/valeria_amezcua.webp', '/speakers/ena_gutierrez_v2.webp', ''],
      id: [2, 13]
    },
  ],
  day_3: [
    {
      type:'Panel',
      type_en:'Panel',
      duration:'45 min',
      timetable:'10:00 - 10:45',
      title:'Regulación de almacenamiento de energía eléctrica',
      title_en:'Regulation of electrical energy storage',
      subject:'Electromobilidad',
      subject_en:'Electromobility',
      description:'',
      description_en:'',
      peakers:'Patricia Tattó | José María Lijambio',
      position:'Ata Renewables | CCN',
      position_en: 'Ata Renewables | CCN',
      avatars: ['', '', ''],
      id: []
    },
    {
      type:'Panel',
      type_en:'Panel',
      duration:'45 min',
      timetable:'10:45 - 11:30',
      title:'Aplicaciones de Hidrógeno Verde para México',
      title_en:'Green Hydrogen Applications for Mexico',
      subject:'Almacenamiento',
      subject_en:'Storage',
      description:'',
      description_en:'',
      peakers:'Luisa Sierra Brozon | Lorena Espinosa',
      position:'IMC | GIZ',
      position_en: 'IMC | GIZ',
      avatars: ['/speakers/luisa_sierra.webp', '', ''],
      id: [9]
    },
    {
      type: 'Panel',
      type_en: 'Panel',
      duration: '45 min',
      timetable: '11:30 - 12:15',
      title: 'Electromovilidad y energía renovable',
      title_en: 'Electromobility and renewable energy',
      subject: 'Hidrógeno Verde',
      subject_en: 'Green Hydrogen',
      description: '',
      description_en: '',
      peakers: 'Carla Ortiz | Diana Ávalos | Jesús Antonio del Río Portillo',
      position: 'RER | AMIVE | IER-UNAM ',
      position_en: 'RER | AMIVE | IER-UNAM',
      avatars: ['', '/speakers/diana_avalos.webp', '/speakers/antonio-portillo.webp'],
      id: [,10, 15]
    },
    // {
    //   type:'',
    //   type_en:'',
    //   duration:'0 min',
    //   timetable:'00:00 - 00:00',
    //   title:'',
    //   title_en:'',
    //   subject:'',
    //   subject_en:'',
    //   description:'',
    //   description_en:'',
    //   peakers:'',
    //   position:'',
    //   position_en:''
    // },
  ]
}

export { programSSM, conferencesSSM }
