const speakers=[
    {
        id:1,
        name: 'Angélica Soto',
        avatar: '/speakers/angelica_soto.webp',
        role_es: "Directora General Nx Buena Energía",
        role_en: "General Manager Nx Buena Energía",
        resume_es: 'Ha contribuido al crecimiento y consolidación del Grupo Nexus Energía, una empresa con más de 23 años de experiencia líder en gestión de activos renovables y una de las primeras comercializadoras de electricidad en el mercado liberalizado español.',
        resume_en: 'She has contributed to the growth and consolidation of Grupo Nexus Energía, a company with more than 23 years of experience as a leader in asset management. 23 years of experience, leader in the management of renewable and one of the leading electricity traders in the Spanish deregulated market.',
    },
    {
        id:2,
        name: 'Valeria Amezcua',
        avatar: '/speakers/valeria_amezcua.webp',
        role_es: "Presidenta, Red Agrovoltaica Mexicana",
        role_en: "President, Mexican Agrovoltaic Network",
        resume_es: 'Con 9 años de experiencia en descarbonización y democratización de la energía, ha liderado el desarrollo y evaluación de regulaciones en la Comisión Reguladora de Energía. Actualmente, en VIA Climate Solutions, desarrolla estrategias de descarbonización, imparte cátedra sobre los Objetivos de Desarrollo Sostenible y preside la Red Agrovoltaica Mexicana, promoviendo la aplicación integral de la energía solar.',
        resume_en: 'With 9 years of experience in decarbonization and energy democratization democratization of energy, he has led the development and evaluation of regulations at the Energy Regulatory Energy Regulatory Commission. Currently, at VIA Climate Solutions, he develops decarbonization strategies, teaches on the strategies, teaches on Sustainable Development Goals and chairs the Mexican Agrovoltaic Network, promoting the Agrovoltaic Network, promoting the integral application of solar energy.',
    },
    {
        id:3,
        name: 'Mario S. DePillis Jr.',
        avatar: '/speakers/mario_pillis.webp',
        role_es: "Experto en el mercado mayorista de la electricidad",
        role_en: "Wholesale Electricity Market Competition Expert",
        resume_es: 'Con más de 25 años de experiencia en el análisis y diseño de mercados eléctricos a nivel internacional. Durante su gestión en el Monitor Independiente del Mercado Eléctrico Mayorista en México, introdujo cambios que ahorraron 1.300 millones de dólares en el primer año. Además, ha contribuido significativamente en proyectos de investigación para el Departamento de Energía de los Estados Unidos.',
        resume_en: 'With more than 25 years of experience in the analysis and design of international electricity markets. at an international level. During his tenure at the Independent Monitor of the Wholesale Electricity Mexico, he introduced changes that saved US$1.3 billion in the first year. 1.3 billion dollars in the first year. In addition, he has contributed significantly research projects for the U.S. Department of Energy.',
    },
    {
        id:4,
        name: 'Luis Gerardo Sánchez Stone',
        avatar: '/speakers/luis_sanchez.webp',
        role_es: "Director General en ErgoSolar",
        role_en: "General Manager at ErgoSolar",
        resume_es: 'Luis es el fundador de ErgoSolar, empresa líder en energía solar desde 2010. Ha sido reconocido por sus contribuciones en energía y diseño de dispositivos médicos patentados. Además, preside la comisión de energía en COPARMEX Puebla y es miembro fundador de asociaciones de energía solar. Su compromiso radica en desarrollar tecnología sostenible para México e internacionalmente.',
        resume_en: 'Luis is the founder of ErgoSolar, a leading solar energy company since 2010. He has been recognized for his contributions in energy and patented medical device design. In addition, he chairs the energy commission at COPARMEX Puebla and is a founding member of solar energy associations. His commitment lies in developing sustainable technology for Mexico and internationally.',
    },
    // {
    //     id:5,
    //     name: 'Enrique Garduño',
    //     avatar: '/speakers/enrique_gardunno.webp',
    //     role_es: "CEO Skysense",
    //     role_en: "CEO Skysense",
    //     resume_es: 'Fundador y Director General de Skysense, ha impulsado más de 800 proyectos en operación. Su enfoque en soluciones fotovoltaicas y de almacenamiento, así como en sistemas híbridos y microrredes, ha dejado una huella significativa en la industria. Su compromiso con la promoción de prácticas empresariales responsables y sostenibles lo convierte en un referente destacado en el sector de la energía.',
    //     resume_en: 'Founder and CEO of Skysense, he has driven more than 800 projects in operation. His focus on photovoltaic and storage solutions, as well as hybrid systems and microgrids, has left a significant footprint in the industry. His commitment to promoting responsible and sustainable business practices makes him a leading reference in the energy sector.',
    // },
    {
        id:6,
        name: "Eduardo Gómez",
        avatar: '/speakers/eduardo_gomez.webp',
        role_es: "Director Comercial, LATAM Maxeon Solar Technologies",
        role_en: "Sales Director, LATAM Maxeon Solar Technologies",
        resume_es: "Información en proceso",
        resume_en: "Information in process",
    },
    {
        id:7,
        name: "Jesús Carrillo",
        avatar: '/speakers/jesus_carrillo.webp',
        role_es: "Director de Economía, en el Instituto Mexicano para la Competitvidad A.C. (IMCO)",
        role_en: "Director of Economics, Instituto Mexicano para la Competitvidad A.C. (IMCO).",
        resume_es: "Destacado ingeniero mecánico convertido en economista, con una sólida formación académica que incluye una maestría y un doctorado en Economía por El Colegio de México (Colmex). Actualmente, se desempeña como docente por asignatura en esta prestigiosa institución, donde también ha colaborado como investigador invitado del Programa en Energía durante el periodo 2019-2020. En su rol como precursor de una agenda de investigación en economía sostenible en el Instituto Mexicano para la Competitividad (IMCO), Jesús Carrillo lidera un equipo de investigadores enfocados en analizar diversos temas, como energía, medio ambiente, mercado laboral, comercio internacional y finanzas públicas. Su trabajo busca establecer vínculos entre estas áreas y las políticas públicas nacionales, así como las condiciones socioambientales en México. Antes de unirse al IMCO, desempeñó un papel crucial en el sector energético mexicano, desarrollando metodologías de análisis estadístico y económico en la Comisión Nacional de Hidrocarburos. Su experiencia lo llevó a crear y liderar el área de dictaminación de planes y presupuestos de los operadores petroleros en el país.Como miembro de la Fox International Fellowship de la Universidad de Yale en 2020-2021, Jesús Carrillo realizó investigaciones sobre el sector energético mexicano, centrándose en el mercado de gasolinas y la reforma energética de 2013 en México. Además, es colaborador en El Economista y ha contribuido con artículos en revistas mexicanas como Gatopardo, Letras Libres y Nexos, entre otros medios de comunicación.",
        resume_en: "Prominent mechanical engineer turned economist, with a solid academic background including a master's degree and a PhD in Economics from El Colegio de México (Colmex). He currently serves as an adjunct professor at this prestigious institution, where he has also collaborated as a visiting researcher in the Energy Program during the 2019-2020 period. In his role as a precursor of a sustainable economics research agenda at the Mexican Institute for Competitiveness (IMCO), Jesús Carrillo leads a team of researchers focused on analyzing various topics such as energy, environment, labor market, international trade and public finances. His work seeks to establish links between these areas and national public policies, as well as socio-environmental conditions in Mexico. Prior to joining IMCO, he played a crucial role in the Mexican energy sector, developing statistical and economic analysis methodologies at the National Hydrocarbons Commission. His experience led him to create and lead the area of review of plans and budgets of oil operators in the country.",
    },
    {
        id:8,
        name: "Jorge Villarreal Padilla",
        avatar: '/speakers/jorge_villarreal.webp',
        role_es: "Director de Política Climática. ICM",
        role_en: "Director of Climate Policy. ICM",
        resume_es: "Miembro fundador de la Iniciativa Climática de México (ICM), donde actualmente es Director de Política Climática. ICM es una organización de la sociedad civil, sin fines de lucro, que desde el 2011 diseña e impulsa la implementación de políticas, programas y proyectos de mitigación de gases de efecto invernadero. Como responsable de la agenda de política climática de ICM, ha estado a cargo de la estrategia del área y la gestión de los proyectos en la misma. Ha participado en el diseño y promoción de instrumentos legales y de política pública claves para la acción climática y la transición energética en México. Desde el 2017 es integrante del Consejo Directivo de la Iniciativa de Transparencia Climática, un consorcio global de think-tanks que buscan estimular la acción climática en las economías de G20; y desde el 2021 es integrante del Consejo Directivo de la Iniciativa para la Divulgación de Activos Climáticos de América Latina, que busca contribuir a que los flujos financieros sean coherentes con los objetivos del Acuerdo de París. Es autor, coautor y revisor de diversos reportes internacionales que evalúan el desempeño de la acción climática, como el Reporte de la Transparencia Climática, el Reporte de la Brecha de Emisiones y el Reporte de la Brecha de Producción, el Reporte EMBER, entre otros.",
        resume_en: "Founding Member of the Mexico Climate Initiative (ICM), where he is currently Climate Policy Director. ICM is a non-profit civil society organization that since 2011 designs and promotes the implementation of greenhouse gas mitigation policies, programs and projects. As head of ICM's climate policy agenda, he has been in charge of the area's strategy and project management. He has participated in the design and promotion of key legal instruments and public policies for climate action and the energy transition in Mexico. Since 2017 he is a member of the Board of Directors of the Climate Transparency Initiative, a global consortium of think tanks that seek to stimulate climate action in G20 economies; and since 2021 he is a member of the Board of Directors of the Latin America Climate Asset Disclosure Initiative, which seeks to contribute to making financial flows consistent with the objectives of the Paris Agreement. He is the author, co-author and reviewer of several international reports that assess the performance of climate action, such as the Climate Transparency Report, the Emissions Gap Report and the Production Gap Report, the EMBER Report, among others.",
    },
    {
        id:9,
        name: "Luisa Sierra Brozon",
        avatar: '/speakers/luisa_sierra.webp',
        role_es: "Directora del Programa de Energía dentro de la Iniciativa Climática de México (ICM).",
        role_en: "Director of the Energy Program within the Mexico Climate Initiative (ICM).",
        resume_es: "Directora del Programa de Energía dentro de la Iniciativa Climática de México (ICM). Es Arquitecta y cuenta con una maestría en planeación y desarrollo urbano por University College London, en donde realizó un análisis socio tecnológico del sector de generación y consumo de energía eléctrica en México desde un enfoque social. Cuenta con dos diplomados: Uno en matemáticas y estadísticas por el Museo Interactivo de Economía (MIDE).; y otro en finanzas corporativas por el Instituto Tecnológico Autónomo de México (ITAM).  Tiene más de 10 años de experiencia en temas relacionados con cambio climático; y es autora y coautora de diversas publicaciones y reportes en materia de cambio climático, energía y transporte. Actualmente, tiene a su cargo la coordinación e implementación de la agenda relacionada con el área de Energía de ICM, en donde es responsable de identificar necesidades y prioridades de políticas públicas; comprender el contexto de la política climática y la información técnica relacionada con las emisiones y el potencial de mitigación en el sector energético de México. Además, está a cargo de construir y fomentar la relación de ICM con actores clave del sector público y privado; dirigir esfuerzos de recomendación de alto nivel sobre la importancia de los objetivos nacionales de mitigación. Tiene experiencia supervisando y coordinando proyectos sobre medidas de mitigación de gases de efecto invernadero, políticas de planeación del sector eléctrico, transporte de carga y electromovilidad, sector petróleo y gas, teoría de transiciones para el sector energía, eficiencia energética y energía solar fotovoltaica.",
        resume_en: "Director of the Energy Program within the Mexico Climate Initiative (ICM). She is an Architect and holds a master's degree in urban planning and development from University College London, where she conducted a socio-technological analysis of the electricity generation and consumption sector in Mexico from a social approach. She has two certificates: One in mathematics and statistics from the Interactive Museum of Economics (MIDE); and another one in corporate finance from the Autonomous Technological Institute of Mexico (ITAM). She has over 10 years of experience in climate change related issues; and is the author and co-author of several publications and reports on climate change, energy and transport. Currently, she is in charge of coordinating and implementing ICM's Energy area agenda, where she is responsible for identifying public policy needs and priorities; understanding the context of climate policy and technical information related to emissions and mitigation potential in Mexico's energy sector. In addition, she is in charge of building and fostering ICM's relationship with key public and private sector stakeholders; directing high-level recommendation efforts on the importance of national mitigation goals. She has experience supervising and coordinating projects on greenhouse gas mitigation measures, electric sector planning policies, freight transport and electric mobility, oil and gas sector, transition theories for the energy sector, energy efficiency and solar photovoltaics.",
    },
]
export { speakers }
  