const speakers=[
    {
        id:1,
        name: 'Angélica Soto',
        avatar: '/speakers/angelica_soto.webp',
        role_es: "Directora General Nx Buena Energía",
        role_en: "General Manager Nx Buena Energía",
        resume_es: 'Con más de 15 años de experiencia en el sector eléctrico, ha contribuido al crecimiento y consolidación del Grupo Nexus Energía, una empresa con más de 23 años de experiencia líder en gestión de activos renovables y una de las primeras comercializadoras de electricidad en el mercado liberalizado español. Actualmente, es directora general de Nx Buena Energía, empresa especializada en Mercado Eléctrico Mayorista y proveedora integral de soluciones energética a Generadores y Consumidores de Energía Eléctrica. Es miembro del Consejo de Dirección de la principal Asociación Mexicana de Energía Solar (ASOLMEX), integrante de MERM (Mujeres de Energía Renovable) y Voz Experta. Es Ingeniera Industrial en Calidad, egresada de la Universidad La Salle Chihuahua; posee un Máster en Ingeniería y Gestión de las Energías Renovables, de la Universidad de Barcelona; y un programa de Liderazgo para Mujeres, del Qiyadat en la Georgetown University McDonough School of Business.',
        resume_en: 'With over 15 years of experience in the electricity sector, she has contributed to the growth and consolidation of Grupo Nexus Energía, a company with more than 23 years of experience leading in renewable asset management and one of the first electricity retailers in the liberalized Spanish market. Currently, she is the General Director of Nx Buena Energía, a company specialized in the Wholesale Electricity Market and a comprehensive provider of energy solutions to Electricity Generators and Consumers. She is a member of the Board of Directors of the main Mexican Solar Energy Association (ASOLMEX), a member of MERM (Women in Renewable Energy), and an Expert Voice. She holds a Bachelor\'s degree in Industrial Quality Engineering from Universidad La Salle Chihuahua, a Master\'s degree in Renewable Energy Engineering and Management from the University of Barcelona, and a Women\'s Leadership program from Qiyadat at Georgetown University\'s McDonough School of Business',
    },
    {
        id:2,
        name: 'Valeria Amezcua',
        avatar: '/speakers/valeria_amezcua.webp',
        role_es: "Presidenta, Red Agrovoltaica Mexicana",
        role_en: "President, Mexican Agrovoltaic Network",
        resume_es: 'Ingeniera Química por la Universidad Iberoamericana y Maestra en Energía y Sustentabilidad por la Universidad de Southampton. Desde hace 9 años, se ha especializado en la descarbonización y democratización de la energía, destacando su labor en el desarrollo y evaluación de regulaciones en la Comisión Reguladora de Energía. Actualmente, desarrolla estrategias de descarbonización en VIA Climate Solutions. Imparte cátedra sobre los Objetivos de Desarrollo Sostenible y es la Presidenta de la Red Agrovoltaica Mexicana, organización que busca promover una aplicación integral de la energía solar.',
        resume_en: 'Chemical Engineer from the Universidad Iberoamericana and Master in Energy and Sustainability from the University of Southampton. For 9 years, she has specialized in the decarbonization and democratization of energy, highlighting her work in the development and evaluation of regulations at the Energy Regulatory Commission. She currently develops decarbonization strategies at VIA Climate Solutions. She teaches about the Sustainable Development Goals and is the President of the Mexican Agrivoltaic Network, an organization that seeks to promote an integral application of solar energy.',
    },
    {
        id:3,
        name: 'Mario S. DePillis Jr.',
        avatar: '/speakers/mario_pillis.webp',
        role_es: "Miembro de Cigré y de la American Economic Association",
        role_en: "Member of Cigré and the American Economic Association",
        resume_es: 'Economista, consejero de admonitor, experto en mercados eléctricos, diseño de mercados y supervisión de mercados. Lleva más de 25 años revisando y diseñando mercados de electricidad, ya sea como miembro de un operador del mercado, como supervisor del mercado o como regulador. Fue Director del Monitor Independiente del Mercado Eléctrico Mayorista de México desde diciembre de 2015 hasta 2020. Ha realizado investigaciones para el Departamento de Energía de EE.UU. y asesora a clientes sobre cuestiones relacionadas con el mercado mayorista de la electricidad y con transmisión. Como director del consejo de asesores de Admonitor, proporciona a Admonitor asesoramiento estratégico y experiencia. Ha trabajado con mercados de Sudamérica, Vietnam, Centroamérica y Estados Unidos.',
        resume_en: 'Economist, advisor to admonitor, expert in electricity markets, market design and market supervision. He has been reviewing and designing electricity markets for more than 25 years, either as a member of a market operator, as a market monitor or as a regulator. He was Director of the Independent Monitor of the Mexican Wholesale Electricity Market from December 2015 to 2020. He has conducted research for the U.S. Department of Energy and advises clients on wholesale electricity market and transmission issues. As a director on Admonitor\'s advisory board, he provides Admonitor with strategic advice and expertise. He has worked with markets in South America, Vietnam, Central America and the United States.'
    },
    {
        id:4,
        name: 'Luis Gerardo Sánchez Stone',
        avatar: '/speakers/luis_sanchez.webp',
        role_es: "Director General en ErgoSolar",
        role_en: "General Manager at ErgoSolar",
        resume_es: 'Fundador de ErgoSolar, empresa líder en energía solar desde 2010. Ha sido reconocido por sus contribuciones en energía y diseño de dispositivos médicos patentados. Además, preside la comisión de energía en COPARMEX Puebla y es miembro fundador de asociaciones de energía solar. Su compromiso radica en desarrollar tecnología sostenible para México e internacionalmente.',
        resume_en: 'Founder of ErgoSolar, a leading solar energy company since 2010. He has been recognized for his contributions in energy and design of patented medical devices. Additionally, he chairs the energy commission at COPARMEX Puebla and is a founding member of solar energy associations. His commitment lies in developing sustainable technology for Mexico and internationally.',
    },
    // {
    //     id:5,
    //     name: 'Enrique Garduño',
    //     avatar: '/speakers/enrique_gardunno.webp',
    //     role_es: "CEO Skysense",
    //     role_en: "CEO Skysense",
    //     resume_es: 'Fundador y Director General de Skysense, ha impulsado más de 800 proyectos en operación. Su enfoque en soluciones fotovoltaicas y de almacenamiento, así como en sistemas híbridos y microrredes, ha dejado una huella significativa en la industria. Su compromiso con la promoción de prácticas empresariales responsables y sostenibles lo convierte en un referente destacado en el sector de la energía.',
    //     resume_en: 'Founder and CEO of Skysense, he has driven more than 800 projects in operation. His focus on photovoltaic and storage solutions, as well as hybrid systems and microgrids, has left a significant footprint in the industry. His commitment to promoting responsible and sustainable business practices makes him a leading reference in the energy sector.',
    // },
    {
        id:6,
        name: "Eduardo Gómez",
        avatar: '/speakers/eduardo_gomez.webp',
        role_es: "Director comercial para Latinoamérica en Maxeon Solar Technologies",
        role_en: "Sales Director for Latin America at Maxeon Solar Technologies",
        resume_es: "Director comercial para Latinoamérica en Maxeon Solar Technologies (fabricante de paneles solares líder en el segmento premium) desde 2021, colaborando en el desarrollo de la generación distribuida en diferentes mercados. Anteriormente, tuvo posiciones directivas por 15 años en las industrias de tecnología, electrónicos y línea blanca, en Sony Electronics y Electrolux Home Appliances, desarrollando varios territorios de América Latina. Es doctor en ciencias administrativas por el Instituto Universitario Veracruzano, tiene una maestría en desarrollo organizacional por la Universidad de Guanajuato y es Ingeniero Industrial por la Universidad de las Américas, Puebla.",
        resume_en: "Sales Director for Latin America at Maxeon Solar Technologies (leading solar panel manufacturer in the premium segment) since 2021, collaborating in the development of distributed generation in different markets. Previously, he held management positions for 15 years in the technology, electronics and white goods industries at Sony Electronics and Electrolux Home Appliances, developing several territories in Latin America. He holds a doctorate in administrative sciences from the Instituto Universitario Veracruzano, a master's degree in organizational development from the University of Guanajuato and an industrial engineering degree from the Universidad de las Américas, Puebla.",
    },
    {
        id:7,
        name: "Jesús Carrillo",
        avatar: '/speakers/jesus_carrillo.webp',
        role_es: "Director de Economía, en el Instituto Mexicano para la Competitvidad A.C. (IMCO)",
        role_en: "Director of Economics, Instituto Mexicano para la Competitvidad A.C. (IMCO).",
        resume_es: "Destacado ingeniero mecánico convertido en economista, con una sólida formación académica que incluye una maestría y un doctorado en Economía por El Colegio de México. Actualmente, se desempeña como docente por asignatura en esta prestigiosa institución, donde también ha colaborado como investigador invitado del Programa en Energía durante el periodo 2019-2020. En su rol como precursor de una agenda de investigación en economía sostenible en el Instituto Mexicano para la Competitividad (IMCO), lidera un equipo de investigadores enfocados en analizar diversos temas, como energía, medio ambiente, mercado laboral, comercio internacional y finanzas públicas. Su trabajo busca establecer vínculos entre estas áreas y las políticas públicas nacionales, así como las condiciones socioambientales en México. Antes de unirse al IMCO, desempeñó un papel crucial en el sector energético mexicano, desarrollando metodologías de análisis estadístico y económico en la Comisión Nacional de Hidrocarburos. Su experiencia lo llevó a crear y liderar el área de dictaminación de planes y presupuestos de los operadores petroleros en el país.Como miembro de la Fox International Fellowship de la Universidad de Yale en 2020-2021, realizó investigaciones sobre el sector energético mexicano, centrándose en el mercado de gasolinas y la reforma energética de 2013 en México. Además, es colaborador en El Economista y ha contribuido con artículos en revistas mexicanas como Gatopardo, Letras Libres y Nexos, entre otros medios de comunicación.",
        resume_en: "Prominent mechanical engineer turned economist, with a solid academic background that includes a master's and doctorate in Economics from El Colegio de México. He currently serves as an adjunct professor at this prestigious institution, where he has also collaborated as a visiting researcher in the Energy Program during the period 2019-2020. In his role as a pioneer of a sustainable economics research agenda at the Mexican Institute for Competitiveness (IMCO), he leads a team of researchers focused on analyzing various topics such as energy, the environment, labor market, international trade, and public finances. His work seeks to establish links between these areas and national public policies, as well as socio-environmental conditions in Mexico. Before joining IMCO, he played a crucial role in the Mexican energy sector, developing statistical and economic analysis methodologies at the National Hydrocarbons Commission. His experience led him to create and lead the area of assessment of plans and budgets for oil operators in the country. As a member of Yale University's Fox International Fellowship in 2020-2021, he conducted research on the Mexican energy sector, focusing on the gasoline market and the 2013 energy reform in Mexico. Additionally, he is a collaborator at El Economista and has contributed articles to Mexican magazines such as Gatopardo, Letras Libres, and Nexos, among other media.",
    },
    {
        id:8,
        name: "Jorge Villarreal Padilla",
        avatar: '/speakers/jorge_villarreal.webp',
        role_es: "Director de Política Climática. ICM",
        role_en: "Director of Climate Policy. ICM",
        resume_es: "Miembro fundador de la Iniciativa Climática de México (ICM), donde actualmente es Director de Política Climática. ICM es una organización de la sociedad civil, sin fines de lucro, que desde el 2011 diseña e impulsa la implementación de políticas, programas y proyectos de mitigación de gases de efecto invernadero. Como responsable de la agenda de política climática de ICM, ha estado a cargo de la estrategia del área y la gestión de los proyectos en la misma. Ha participado en el diseño y promoción de instrumentos legales y de política pública claves para la acción climática y la transición energética en México. Desde el 2017 es integrante del Consejo Directivo de la Iniciativa de Transparencia Climática, un consorcio global de think-tanks que buscan estimular la acción climática en las economías de G20; y desde el 2021 es integrante del Consejo Directivo de la Iniciativa para la Divulgación de Activos Climáticos de América Latina, que busca contribuir a que los flujos financieros sean coherentes con los objetivos del Acuerdo de París. Es autor, coautor y revisor de diversos reportes internacionales que evalúan el desempeño de la acción climática, como el Reporte de la Transparencia Climática, el Reporte de la Brecha de Emisiones y el Reporte de la Brecha de Producción, el Reporte EMBER, entre otros.",
        resume_en: "Founding Member of the Mexico Climate Initiative (ICM), where he is currently Climate Policy Director. ICM is a non-profit civil society organization that since 2011 designs and promotes the implementation of greenhouse gas mitigation policies, programs and projects. As head of ICM's climate policy agenda, he has been in charge of the area's strategy and project management. He has participated in the design and promotion of key legal instruments and public policies for climate action and the energy transition in Mexico. Since 2017 he is a member of the Board of Directors of the Climate Transparency Initiative, a global consortium of think tanks that seek to stimulate climate action in G20 economies; and since 2021 he is a member of the Board of Directors of the Latin America Climate Asset Disclosure Initiative, which seeks to contribute to making financial flows consistent with the objectives of the Paris Agreement. He is the author, co-author and reviewer of several international reports that assess the performance of climate action, such as the Climate Transparency Report, the Emissions Gap Report and the Production Gap Report, the EMBER Report, among others.",
    },
    {
        id:9,
        name: "Luisa Sierra Brozon",
        avatar: '/speakers/luisa_sierra.webp',
        role_es: "Directora del Programa de Energía dentro de la Iniciativa Climática de México (ICM).",
        role_en: "Director of the Energy Program within the Mexico Climate Initiative (ICM).",
        resume_es: "Directora del Programa de Energía dentro de la Iniciativa Climática de México (ICM). Es Arquitecta y cuenta con una maestría en planeación y desarrollo urbano por University College London, en donde realizó un análisis socio tecnológico del sector de generación y consumo de energía eléctrica en México desde un enfoque social. Cuenta con dos diplomados: uno en Matemáticas y Estadísticas, por el Museo Interactivo de Economía; y otro en Finanzas corporativas, por el Instituto Tecnológico Autónomo de México (ITAM). Tiene más de 10 años de experiencia en temas relacionados con cambio climático, es autora y coautora de diversas publicaciones y reportes en materia de cambio climático, energía y transporte. Actualmente, tiene a su cargo la coordinación e implementación de la agenda relacionada con el área de Energía de ICM, en donde es responsable de identificar necesidades y prioridades de políticas públicas, comprender el contexto de la política climática y la información técnica relacionada con las emisiones y el potencial de mitigación en el sector energético de México. Además, está a cargo de construir y fomentar la relación de ICM con actores clave del sector público y privado, así como dirigir esfuerzos de recomendación de alto nivel sobre la importancia de los objetivos nacionales de mitigación. Tiene experiencia supervisando y coordinando proyectos sobre medidas de mitigación de gases de efecto invernadero, políticas de planeación del sector eléctrico, transporte de carga y electromovilidad, sector petróleo y gas, teoría de transiciones para el sector energía, eficiencia energética y energía solar fotovoltaica.",
        resume_en: "Director of the Energy Program within the Mexico Climate Initiative (ICM). She is an Architect and holds a master's degree in urban planning and development from University College London, where she conducted a socio-technological analysis of the electricity generation and consumption sector in Mexico from a social perspective. She has two diplomas: one in Mathematics and Statistics from the Interactive Museum of Economics, and another in Corporate Finance from the Autonomous Technological Institute of Mexico (ITAM). She has more than 10 years of experience in climate change-related issues, is the author and co-author of various publications and reports on climate change, energy, and transportation. Currently, she is in charge of coordinating and implementing the agenda related to the Energy area of ICM, where she is responsible for identifying public policy needs and priorities, understanding the context of climate policy and technical information related to emissions and mitigation potential in the Mexican energy sector. Additionally, she is in charge of building and fostering ICM's relationship with key actors in the public and private sectors, as well as directing high-level advisory efforts on the importance of national mitigation goals. She has experience supervising and coordinating projects on greenhouse gas mitigation measures, electricity sector planning policies, freight transportation and electromobility, oil and gas sector, energy sector transition theory, energy efficiency, and photovoltaic solar energy.",
    },
    {
        id:10,
        name: "Diana Ávalos",
        avatar: '/speakers/diana_avalos.webp',
        role_es: "AMIVE",
        role_en: "AMIVE",
        resume_es: "Egresada de la la carrera de Ciencia Política, de la Facultad de Ciencias Políticas y Sociales de la Universidad Nacional Autónoma de México. Ha colaborado por más de nueve años como asesora de cambio climático en la Embajada Británica en México, con un enfoque en política climática, movilidad sostenible y finanzas verdes. Antes, formó parte de la práctica de consultoría para sector gobierno en PWC México.",
        resume_en: "Graduated from the Political Science program at the Faculty of Political and Social Sciences of the National Autonomous University of Mexico. She has worked for over nine years as a climate change advisor at the British Embassy in Mexico, focusing on climate policy, sustainable mobility, and green finance. Previously, she was part of the government sector consulting practice at PwC Mexico.",
    },
    {
        id:11,
        name: " Dra. Carolin Antoni",
        avatar: '/speakers/carolin_antoni.webp',
        role_es: "Gerente del departamento de desarrollo sostenible de CAMEXA",
        role_en: "Manager of the sustainable development department of CAMEXA",
        resume_es: "Especialista en Educación para el Desarrollo Sostenible, Ciencias ambientales, Sistemas Socioecológicos, y Resiliencia, cuenta con una maestría y un doctorado en Ciencias Ambientales; además, cuenta con diversos diplomados y certificaciones. Es gerente del departamento de desarrollo sostenible de CAMEXA. Antes de iniciar a su cargo en CAMEXA colaboró en el departamento de Comercio Exterior en la Embajada de Austria en México. Se ha dedicado a temas relacionados con el medio ambiente desde hace 20 años y con un enfoque especial en la sostenibilidad desde 2008. Ha trabajado en diversas instituciones académicas, por ejemplo en el Instituto Fraunhofer de Sistemas de Energía Solar ISE y en la iniciativa privada. Asimismo, ha trabajado en diversos grupos interdisciplinarios, especialmente en cuestiones relacionadas con métodos participativos con diferentes actores para un desarrollo sostenible.",
        resume_en: "Specialist in Education for Sustainable Development, Environmental Sciences, Socio-ecological Systems, and Resilience, she holds a master's degree and a doctorate in Environmental Sciences, as well as various diplomas and certifications. She is the manager of the sustainable development department at CAMEXA. Before starting her role at CAMEXA, she collaborated in the Foreign Trade department at the Austrian Embassy in Mexico. She has been dedicated to environmental issues for 20 years, with a special focus on sustainability since 2008. She has worked at various academic institutions, for example at the Fraunhofer Institute for Solar Energy Systems ISE and in private initiative. Additionally, she has worked in various interdisciplinary groups, especially on issues related to participatory methods with different actors for sustainable development.",
    },
    {
        id:12,
        name: "Ana Lilia Moreno ",
        avatar: '/speakers/ana_lilia.webp',
        role_es: "Coordinadora e investigadora del Programa de Regulación y Competencia Económica en México Evalúa",
        role_en: "Coordinator and researcher of the Regulation and Economic Competition Program at México Evalúa",
        resume_es: "Economista por la Universidad Panamericana, tiene una Maestría en Economía por la Universidad de East Anglia, Reino Unido, y estudios especializados en Ciencia Política en la Universidad de Notre Dame. Actualmente, es coordinadora e investigadora del Programa de Regulación y Competencia Económica en México Evalúa. Su labor reciente se ha enfocado en la transición energética en México a niveles nacional y subnacional, en temas de gobierno corporativo y sustentabilidad para las Empresas Productivas del Estado, y en la compleja paradoja energética que vive México ante los retos del TMEC y de procurar una seguridad energética eficaz y sostenible. Su experiencia también se refleja en la mejora regulatoria, competencia económica, gobierno corporativo y el estándar ESG en instituciones clave como Pemex y CFE, además de su contribución en políticas contra la pobreza energética. Con una amplia trayectoria, desde CIDAC, dirigió estrategias de investigación y comunicación para explicar al público los procesos y significado de las reformas estructurales que se dieron en el 2013. De 2015 a 2017 colaboró en Instituto Federal de Telecomunicaciones como Directora de área en temas de competencia económica y regulación. Previamente, acumuló más de una década como gerente senior de precios de transferencia en Deloitte y KPMG. Además, es docente en la Universidad Anáhuac en temas de Economía Industrial.",
        resume_en: "Economist from Universidad Panamericana, she holds a Master's in Economics from the University of East Anglia, UK, and specialized studies in Political Science from the University of Notre Dame. Currently, she is the coordinator and researcher of the Program on Regulation and Economic Competition at Mexico Evalúa. Her recent work has focused on energy transition in Mexico at both national and subnational levels, corporate governance and sustainability for State Productive Enterprises, and the complex energy paradox Mexico faces amidst the challenges of the USMCA and the pursuit of effective and sustainable energy security. Her expertise also extends to regulatory improvement, economic competition, corporate governance, and ESG standards in key institutions such as Pemex and CFE, as well as her contributions to policies against energy poverty. With a vast trajectory, she directed research and communication strategies at CIDAC, aiming to elucidate to the public the processes and significance of the structural reforms that occurred in 2013. From 2015 to 2017, she collaborated with the Federal Telecommunications Institute as Director of an area focusing on economic competition and regulation. Previously, she accumulated over a decade as a senior transfer pricing manager at Deloitte and KPMG. Additionally, she teaches Industrial Economics at Universidad Anáhuac.",
    },
    {
        id:13,
        name: "Ena Gutiérrez ",
        avatar: '/speakers/ena_gutierrez_v2.webp',
        role_es: "Directora de nuevos negocios en Enlight",
        role_en: "Director of new business at Enlight",
        resume_es: "Ingeniera en Desarrollo Sustentable por el Tecnológico de Monterrey y se ha especializado en el desarrollo de negocios enfocado en microredes y soluciones distribuidas en México y Latinoamérica. Ha sido parte del sector de generación distribuida en México desde hace 8 años. Gracias a su liderazgo en el proyecto, Enlight fue la primera empresa en desarrollar su propio sistema de monitoreo, Apollo. Cuenta con un amplio conocimiento en el desarrollo de proyectos fotovoltaicos y de almacenamiento de energía y debido a ello, se ha dedicado a crear la nueva unidad de negocio de almacenamiento de energía en Enlight. Su rol como Directora de Nuevos Negocios abarca la ejecución del proceso comercial para proyectos fotovoltaicos y de almacenamiento de energía, así como la elaboración del modelo financiero para ofrecer estos proyectos como servicios financiados en el esquema PPA Onsite y SaaS (Storage as a Service). ",
        resume_en: "Engineer in Sustainable Development from Tecnológico de Monterrey and has specialized in business development focused on microgrids and distributed solutions in Mexico and Latin America. She has been part of the distributed generation sector in Mexico for 8 years. Thanks to his leadership in the project, Enlight was the first company to develop its own monitoring system, Apollo. She has extensive knowledge in the development of photovoltaic and energy storage projects and because of this, she has dedicated herself to create the new energy storage business unit at Enlight. Her role as Director of New Business encompasses the execution of the commercial process for PV and energy storage projects, as well as the elaboration of the financial model to offer these projects as PPA Onsite and SaaS (Storage as a Service) financed services. ",
    },
    {
        id:14,
        name: "Celeste Morales",
        avatar: '/speakers/celeste-morales_v2.webp',
        role_es: "IER-UNAM",
        role_en: "IER-UNAM",
        resume_es: "Tiene experiencia en gestión tecnológica, educación continua y comunicación digital. Actualmente, es Titular de la Secretaría de Gestión Tecnológica y Vinculación en el Instituto de Energías Renovables (IER), de la UNAM. Es coautora de libros como (La gobernanza en la Ciudad de México. Visiones multidisciplinarias) y ( México hacia una transición energética ). Ha publicado artículos en la columna ( Sin embargo se mueve), del periódico La Unión de Morelos. Durante su gestión como Jefa de la Unidad de Educación Continua del IER, lideró la creación y mejora de programas educativos, incluyendo la plataforma de aprendizaje en línea ( Renovando Talentos ) . Está comprometida con la excelencia en la educación continua y tiene intereses en comunicación digital, tecnologías de la información, divulgación científica y estudios de género.",
        resume_en: "He has experience in technology management, continuing education and digital communication. Currently, she is Head of the Secretariat of Technology Management and Liaison at the Institute of Renewable Energy (IER), UNAM. She is co-author of books such as (La gobernanza en la Ciudad de México. Visiones multidisciplinarias) and (México hacia una transición energética). She has published articles in the column (Sin embargo se mueve), in the newspaper La Unión de Morelos. During her tenure as Head of the Continuing Education Unit of the IER, she led the creation and improvement of educational programs, including the online learning platform ( Renovando Talentos ) . She is committed to excellence in continuing education and has interests in digital communication, information technologies, scientific dissemination and gender studies.",
    },
    {
        id:15,
        name: "Jesús Antonio del Río Portillo ",
        avatar: '/speakers/antonio-portillo.webp',
        role_es: "IER-UNAM",
        role_en: "IER-UNAM",
        resume_es: "Es Investigador Titular en el Instituto de Energías Renovables y miembro de las Academias Mexicana de Ciencias (AMC), de Ingeniería (AIM), de Ciencias de Morelos (ACMor), de la Sociedad Mexicana de Física (SMF), de la Sociedad Mexicana de Divulgación de la Ciencia y la Técnica (SOMEDICYT y del Sistema Nacional de Investigadores, distinguido con el nivel III. Recibió el Premio Weizmann en 1991, además cuenta con varios premios y reconocimientos como: Medalla Gabino Barreda, Premio Efraím Hernández Xolocotzi en Ciencias Exactas, Premio de la Casa de la Ciencia de la UAEM, Medalla de Honor en Ciencia y Tecnología 2018, otorgada por el Congreso del Estado de Morelos; Medalla VASE (Visión, Asertividad, Sensibilidad y Entendimiento), el Reconocimiento al Mérito Estatal en Investigación REMEI 2021 y Premio Universidad Nacional 2023.",
        resume_en: "He is a Senior Researcher at the Institute of Renewable Energies and a member of the Mexican Academies of Sciences (AMC), Engineering (AIM), Sciences of Morelos (ACMor), the Mexican Society of Physics (SMF), the Mexican Society for the Popularization of Science and Technology (SOMEDICYT) and the National System of Researchers, distinguished with level III. He received the Weizmann Prize in 1991, also has several awards and recognitions such as: the Gabino Barreda Medal, Efraím Hernández Xolocotzi Prize in Exact Sciences, Prize of the House of Science of the UAEM, Medal of Honor in Science and Technology 2018, awarded by the Congress of the State of Morelos; VASE Medal (Vision, Assertiveness, Sensitivity and Understanding), the Recognition of State Merit in Research REMEI 2021 and National University Award 2023.",
    },
    {
        id:16,
        name: "Humberto Alarcón",
        avatar: '/speakers/humberto_alarcon.webp',
        role_es: "SUNECO",
        role_en: "SUNECO",
        resume_es: "Información por confirmar",
        resume_en: "Information to be confirmed",
    },
    {
        id:17,
        name: "Ángel Mejía Santiago",
        avatar: '/speakers/angel_mejia.webp',
        role_es: "Presidente de la Asociación Mexicana de la Industria Fotovoltaica (AMIF)",
        role_en: "President of the Mexican Association of the Photovoltaic Industry (AMIF)",
        resume_es: "Maestro en Ciencias con especialidad en Ingeniería Energética e Ingeniero en Mecatrónica, por el Tecnológico de Monterrey. Además, es Perito en el área de instalaciones solares para el Estado de Jalisco.Funge como Presidente de la Asociación Mexicana de la Industria Fotovoltaica (AMIF) y ha sido consejero de la Asociación Nacional de Energía Solar (ANES). Fue socio fundador y consejero de la asociación de Fabricantes Mexicanos en las Energías Renovables (FAMERAC). Es co-fundador y Chief Executive Officer, de la empresa Inventive Power S.A.P.I. de C.V, empresa reconocida por el Banco Interamericano de Desarrollo como el mejor negocio verde 2013 en América Latina y el Caribe. Fue nombrado Emprendedor del Año 2014, por la revista Expansión.",
        resume_en: "He holds a Master of Science degree in Energy Engineering and Mechatronics Engineering from Tecnológico de Monterrey. In addition, he is an expert in the area of solar installations for the State of Jalisco. He serves as President of the Mexican Association of the Photovoltaic Industry (AMIF) and has been a member of the board of the National Association of Solar Energy (ANES). He was a founding member and board member of the Mexican Association of Renewable Energy Manufacturers (FAMERAC). He is co-founder and Chief Executive Officer of Inventive Power S.A.P.I. de C.V., a company recognized by the Inter-American Development Bank as the best green business 2013 in Latin America and the Caribbean. He was named Entrepreneur of the Year 2014 by Expansión magazine.",
    },
    {
        id:18,
        name: "Casiopea Ramírez Melgar",
        avatar: '/speakers/casiopea_ramirez.webp',
        role_es: "Socia de Fresh Energy Consulting",
        role_en: "Partner of Fresh Energy Consulting",
        resume_es: "Fundadora de Voz Experta, internacionalista y maestra en geopolítica, y se ha especializado en Regulación de Utilities, por el Public Utility Research Center, de la Universidad de Florida. Experta en regulación y análisis de mercado con 20 años de experiencia en proyectos de transición energética. A lo largo de su trayectoria, ha colaborado con empresas multinacionales de energía, así como consultoras dedicadas a proyectos de mitigación y adaptación al cambio climático en México, Centro América y el Sudeste Asiático. Actualmente, es socia de Fresh Energy Consulting, donde lidera los análisis de impacto regulatorio, estudios de inteligencia de mercado y diseño de estrategias de comercialización; además, participa como perita experta en procesos legales del sector electricidad a nivel internacional. Funge como Presidenta y Consejera Fundadora de Voz Experta, iniciativa dedicada a visibilizar expertas en el sector energía.",
        resume_en: "Founder of Voz Experta, internationalist and master in Geopolitics, and has specialized in Utilities Regulation, by the Public Utility Research Center, University of Florida. She is an expert in regulation and market analysis with 20 years of experience in energy transition projects. Throughout her career, she has collaborated with multinational energy companies, as well as consulting firms dedicated to climate change mitigation and adaptation projects in Mexico, Central America and Southeast Asia. Currently, she is a partner at Fresh Energy Consulting, where she leads regulatory impact analysis, market intelligence studies and marketing strategy design; in addition, she participates as an expert in legal processes in the electricity sector at an international level. She serves as President and Founding Advisor of Voz Experta, an initiative dedicated to making women experts in the energy sector visible.",
    },
    {
        id:19,
        name: "Ana Karina Torres",
        avatar: '/speakers/ana_karina_torres.webp',
        role_es: "Consejera independiente en energía eléctrica",
        role_en: "Independent director in electric energy",
        resume_es: "Nombrada Ingeniera del Año 2015, ha dejado una huella significativa en múltiples áreas. Como instructora externa de la STPS, ha compartido su experiencia en eficiencia energética, responsabilidad social y cambio climático, influenciando positivamente a generaciones de profesionales. Su liderazgo en la Agenda 2030 y la sostenibilidad empresarial ha sido fundamental, destacándose como líder nacional en el Consejo Coordinador de Mujeres Empresarias CCME y como promotora de la igualdad de género en el Colegio de Ingenieros Mecánicos Electricistas de Jalisco. Su compromiso con el medio ambiente la ha llevado a ser parte de la Alianza Empresarial por el Clima y a ser reconocida internacionalmente como promotora de los Objetivos de Desarrollo Sostenible. Como ponente en foros de la industria eléctrica y fotovoltaica, ha compartido su conocimiento y visión, inspirando a otros a seguir su ejemplo. En su trayectoria asociativa, ha ocupado cargos directivos en la Asociación de Constructores de Obra Eléctrica de Occidente, contribuyendo al desarrollo y la capacitación profesional en su sector.",
        resume_en: "Named Engineer of the Year 2015, she has left a significant footprint in multiple areas. As an external instructor for the STPS, she has shared her expertise in energy efficiency, social responsibility and climate change, positively influencing generations of professionals. Her leadership in Agenda 2030 and corporate sustainability has been fundamental, standing out as a national leader in the Coordinating Council of Women Entrepreneurs CCME and as a promoter of gender equality in the College of Mechanical and Electrical Engineers of Jalisco. Her commitment to the environment has led her to be part of the Business Climate Alliance and to be recognized internationally as a promoter of the Sustainable Development Goals. As a speaker at forums in the electricity and photovoltaic industry, she has shared her knowledge and vision, inspiring others to follow her example. In her associative trajectory, she has held leadership positions in the Western Electrical Construction Association, contributing to the development and professional training in her sector.",
    },
    {
        id:20,
        name: "Andrew Kiefer McNeill",
        avatar: '/speakers/andrew_kiefer_v2.webp',
        role_es: "Desarrollador de negocios globales en energía",
        role_en: "Global energy business developer",
        resume_es: "Tiene más de 15 años de experiencia en desarrollo de negocios en energía, tanto renovables como hidrocarburos, a nivel global, cubriendo múltiples mercados, incluyendo Latino América. Se ha enfocado en el área de renovables, con proyectos de PV, Almacenamiento, Eólico e Hidrogeno Verde, trabajando con variedad de clientes desde desarrolladores, EPC’s, Fondos de Inversión, compañías de distribución eléctrica, fabricantes, startups de tecnología, entre otros. Formó parte de dos giras de Combate en Irak como US Marine.",
        resume_en: "He has over 15 years of experience in energy business development, both renewable and hydrocarbon, globally, covering multiple markets, including Latin America. He has focused on the renewable area, with PV, Storage, Wind and Green Hydrogen projects, working with a variety of clients from developers, EPC's, Investment Funds, power distribution companies, manufacturers, technology startups, among others. He was part of two Combat tours in Iraq as a US Marine.",
    },
    {
        id:21,
        name: "Gilberto Sánchez Nogueira",
        avatar: '/speakers/gilberto_sanchez.webp',
        role_es: "Secretario Legislativo en la Asociación Nacional de Energía Solar",
        role_en: "National Solar Energy Association Legislative Secretary",
        resume_es: "Con una sólida experiencia de más de 12 años en el sector de Generación Distribuida, ha desempeñado diversos roles clave. Desde asesorar en regulación del sector eléctrico hasta colaborar en programas de mejora en el sector fotovoltaico, su contribución ha sido notable. Además, ha participado en la formulación de políticas energéticas, como en el Programa Especial de Transición Energética, de la SENER en 2016. Su compromiso con el avance del sector se refleja en su participación en foros nacionales e internacionales y en su labor como Secretario Legislativo en la Asociación Nacional de Energía Solar. Certificado por el Consejo de Profesionales de la Energía Fotovoltaica, su experiencia y dedicación son invaluables en el impulso hacia un futuro más sostenible en energía.",
        resume_en: "With a solid experience of more than 12 years in the Distributed Generation sector, he has played several key roles. From advising on electricity sector regulation to collaborating in improvement programs in the photovoltaic sector, his contribution has been remarkable. In addition, he has participated in the formulation of energy policies, such as in the Special Energy Transition Program, by SENER in 2016. His commitment to the advancement of the sector is reflected in his participation in national and international forums and in his work as Legislative Secretary in the National Solar Energy Association. Certified by the Council of Photovoltaic Professionals, his experience and dedication are invaluable in the drive towards a more sustainable energy future.",
    },
    {
        id:22,
        name: "Leonardo Velasco",
        avatar: '/speakers/leonardo_velasco.webp',
        role_es: "Director de Inspecta PV",
        role_en: "Director of Inspecta PV",
        resume_es: "Ingeniero mecánico electricista por el Instituto Tecnológico y de Estudios Superiores de Monterrey (ITESM) y máster en dirección de empresas por el Instituto Panamericano de Alta Dirección de Empresas (IPADE). Es director de Inspecta PV, firma de ingeniería especializada en consultoría e inspecciones a instalaciones fotovoltaicas con base en normas internacionales de la IEC. Sus áreas de expertise son calidad de energía, diseño de experimentos y calidad en instalaciones fotovoltaicas.  Es autor de múltiples publicaciones en torno a sustentabilidad y energías renovables. Es Termógrafo experto certificado, miembro del grupo técnico en energías renovables del Comité de Normalización de ANCE, expresidente de la Asociación Mexicana de la Industria Fotovoltaica (AMIF) y Auditor líder certificado en las normas ISO 9001 en sistemas de gestión de calidad, 14001 en sistemas de gestión ambiental y 45001 en seguridad y salud en el trabajo.",
        resume_en: "Mechanical and electrical engineer from the Monterrey Institute of Technology and Higher Education (ITESM) and master's degree in business administration from the Pan-American Institute for High Business Management (IPADE). He is the director of Inspecta PV, an engineering firm specialized in consulting and inspections of photovoltaic installations based on international IEC standards. His areas of expertise are power quality, design of experiments, and quality in photovoltaic installations. He is the author of multiple publications on sustainability and renewable energies. He is a certified expert Thermographer, a member of the renewable energy technical group of the ANCE Standardization Committee, former president of the Mexican Photovoltaic Industry Association (AMIF), and a certified Lead Auditor in ISO 9001 Quality Management Systems, 14001 Environmental Management Systems, and 45001 Occupational Health and Safety Management Systems standards.",
    },
    {
        id:23,
        name: "Adriana Aragón",
        avatar: '/speakers/adriana-aragon_v2.webp',
        role_es: "Coordinadora de programa, en GIZ",
        role_en: "Program Coordinator, GIZ",
        resume_es: "Con una sólida formación académica en Economía Ambiental y Política y Gestión Energética y Medioambiental, esta profesional ha acumulado una amplia experiencia en el sector público y en organizaciones internacionales. Con títulos de prestigiosas instituciones como la Universidad East Anglia en el Reino Unido y la Facultad Latinoamericana de Ciencias Sociales (FLACSO) en México, además de diplomados complementarios en economía ambiental, su perfil refleja un compromiso con el desarrollo sostenible y la gestión ambiental. Su carrera en el sector público, particularmente en la Secretaría de Medio Ambiente y Recursos Naturales y la Secretaría de Energía, la ha visto liderar iniciativas clave en eficiencia energética, política climática y desarrollo de programas de sustentabilidad. Su trayectoria también incluye roles destacados en la cooperación internacional, como en la GIZ, donde ha coordinado programas importantes para la implementación de la transición energética en México y la promoción del uso del hidrógeno como fuente energética. Como Coordinadora de Programas clave, su labor sigue siendo fundamental en la promoción de políticas y proyectos que abordan los desafíos energéticos y ambientales, tanto a nivel nacional como internacional.",
        resume_en: "With a solid academic background in Environmental Economics and Energy and Environmental Policy and Management, this professional has accumulated extensive experience in the public sector and international organizations. With degrees from prestigious institutions such as the University of East Anglia in the United Kingdom and the Latin American Faculty of Social Sciences (FLACSO) in Mexico, in addition to complementary diplomas in environmental economics, her profile reflects a commitment to sustainable development and environmental management. Her career in the public sector, particularly in the Ministry of Environment and Natural Resources and the Ministry of Energy, has seen her lead key initiatives in energy efficiency, climate policy and sustainability program development. Her trajectory also includes prominent roles in international cooperation, such as at GIZ, where she has coordinated important programs for the implementation of the energy transition in Mexico and the promotion of the use of hydrogen as an energy source. As Key Program Coordinator, her work continues to be instrumental in promoting policies and projects that address energy and environmental challenges, both nationally and internationally.",
    },
    {
        id:24,
        name: "Carla Ortiz",
        avatar: '/speakers/carla-ortiz.webp',
        role_es: "Directora General en México, RER Energy Group",
        role_en: "General Manager in Mexico, RER Energy Group",
        resume_es: "Se unió a RER Energy Group en 2014, mientras completaba una maestría enfocada en Energía Renovable y Negocios, en la Universidad de Duke. Ha sido fundamental en el lanzamiento de la expansión comercial de dicha empresa en el mercado latinoamericano. Actualmente, es responsable de liderar las iniciativas de desarrollo empresarial de RER Energy Group en México y América Latina. Como líder práctica, se basa en su experiencia en desarrollo de nuevos negocios y operaciones, y combina el análisis proactivo, la visión y el enfoque basado en equipo para impulsar la mejora y el éxito organizacional. Bajo su guía, a pesar de un entorno regulatorio complejo y en evolución, RER México ha comenzado a construir algunos proyectos pequeños y está en desarrollo para proyectos sustanciales en los sectores industrial, comercial y agrícola.",
        resume_en: "She joined RER Energy Group in 2014, while completing a master's degree focused on Renewable Energy and Business, at Duke University. He has been instrumental in launching the company's business expansion into the Latin American market. Currently, he is responsible for leading RER Energy Group's business development initiatives in Mexico and Latin America. As a hands-on leader, she draws on her experience in new business development and operations, and combines proactive analysis, vision and a team-based approach to drive organizational improvement and success. Under his guidance, despite a complex and evolving regulatory environment, RER Mexico has begun building some small projects and is in development for substantial projects in the industrial, commercial and agricultural sectors.",
    },
    {
        id:25,
        name: "José María Lujambio",
        avatar: '/speakers/jose-maria.webp',
        role_es: "Abogado especializado en Energía",
        role_en: "Lawyer specialized in Energy",
        resume_es: "El es un destacado abogado especializado en Energía, ha consolidado una trayectoria notable en el ámbito legal desde su incorporación a CCN en 2014, ascendiendo al cargo de Socio en 2018. Su experiencia se ha centrado en asesorar a diversos actores dentro del sector energético, desde la representación de proyectos de centrales eléctricas hasta la consultoría para empresas de gas natural y petrolíferos. Su profundo conocimiento se refleja en sus publicaciones sobre regulación energética y derecho constitucional, y su compromiso se evidencia en su rol como Secretario del Consejo Directivo de la Asociación Mexicana de Energía Solar. Tiene una maestría en Derecho con enfoque en energía, por la Universidad de Texas, en Austin; además, demuestra su dedicación continua a través de su participación en cursos y afiliaciones profesionales, consolidándose como un líder respetado en su campo.",
        resume_en: "He is a prominent lawyer specializing in Energy, has consolidated a remarkable trajectory in the legal field since joining CCN in 2014, rising to the position of Partner in 2018. His experience has focused on advising various players within the energy sector, from representing power plant projects to consulting for natural gas and oil companies. His deep knowledge is reflected in his publications on energy regulation and constitutional law, and his commitment is evident in his role as Secretary of the Board of Directors of the Mexican Solar Energy Association. He holds a Master of Laws degree with a focus on energy from the University of Texas at Austin and demonstrates his continued dedication through his participation in courses and professional affiliations, establishing himself as a respected leader in his field.",
    },
    {
        id:26,
        name: "Patricia Tattó",
        avatar: '/speakers/patricia-tatto.webp',
        role_es: "Asesora en VP Ata Renewables America",
        role_en: "Advisor at VP Ata Renewables America",
        resume_es: "Licenciada en derecho por la Universidad Iberoamericana, con estudios en Derechos Humanos, por la Universidad Birbeck, en Reino Unido. ha dedicado su carrera a desarrollar e impulsar la industria de Energía Renovable en los mercados energéticos internacionales, como asesora técnica y guía de negocios en la creación de estrategias para la industria en nuevos mercados.En VP Ata Renewables America, asesora a toda la cadena de valor sobre la implementación exitosa de proyectos de energía renovable a gran escala. Fundó y es la actual presidenta de Mujeres en Energía Renovable Mexico AC, una organización sin fines de lucro en todo el sector de las energías renovables, con el propósito de empoderar a las mujeres en el campo de la energía renovable en LATAM.",
        resume_en: "With a law degree from the Universidad Iberoamericana, with studies in Human Rights from Birbeck University in the United Kingdom, she has dedicated her career to developing and promoting the Renewable Energy industry in international energy markets, as a technical advisor and business guide in the creation of strategies for the industry in new markets. At VP Ata Renewables America, she advises the entire value chain on the successful implementation of large-scale renewable energy projects. She founded and is the current president of Mujeres en Energía Renovable Mexico AC, a non-profit organization in the entire renewable energy sector, with the purpose of empowering women in the field of renewable energy in LATAM.",
    },
    {
        id:27,
        name: "Nimbe Durán",
        avatar: '/speakers/nimbe-duran.webp',
        role_es: "Titular de la Unidad de Género e Inclusión, en la Comisión Federal de Electricidad (CFE)",
        role_en: "Head of the Gender and Inclusion Unit at the Federal Electricity Commission (CFE).",
        resume_es: "Con una impresionante formación académica que abarca Relaciones Internacionales, Derecho y Políticas Públicas y Género, ha acumulado más de 14 años de experiencia en diversas áreas de la administración pública federal. Desde sus primeros pasos como analista de inteligencia hasta su destacado desempeño como Titular de la Agregaduría Regional en San Diego, California, donde se convirtió en la primera mujer en ocupar dicho cargo, ha dejado una marca indeleble en su carrera. Su paso por la Policía Federal y la Procuraduría General de la República, la consolidó como una líder en Inteligencia y Cooperación Internacional. Además, su labor como asesora y representante de la Secretaría de Gobernación ante la Organización de los Estados Americanos destaca su compromiso con temas de seguridad y género. En 2019, se unió a la Comisión Federal de Electricidad (CFE) con la tarea de establecer la Unidad de Género e Inclusión, demostrando su dedicación a promover la participación de las mujeres en la industria eléctrica y asegurar la integración de la perspectiva de género en proyectos de electrificación. Su trayectoria ejemplar la posiciona como una figura destacada en el campo de la administración pública y la promoción de la igualdad de género.",
        resume_en: "With an impressive academic background that encompasses International Relations, Law and Public Policy and Gender, she has accumulated more than 14 years of experience in various areas of the federal public administration. From her first steps as an intelligence analyst to her outstanding performance as Head of the Regional Attaché Office in San Diego, California, where she became the first woman to hold such position, she has left an indelible mark in her career. Her time in the Federal Police and the Attorney General's Office consolidated her as a leader in Intelligence and International Cooperation. In addition, her work as advisor and representative of the Ministry of the Interior to the Organization of American States highlights her commitment to security and gender issues. In 2019, she joined the Federal Electricity Commission (CFE) with the task of establishing the Gender and Inclusion Unit, demonstrating her dedication to promoting women's participation in the electricity industry and ensuring gender mainstreaming in electrification projects. Her exemplary track record positions her as a leading figure in the field of public administration and the promotion of gender equality.",
    },
]

const speakersEdu=[
    {
        id:1,
        name: 'Alejandro Terán',
        avatar: '/speakers/alejandro_teran.webp',
        role_es: "Director de Construcción en Energía Real",
        role_en: "Director of Construction at Energía Real",
        resume_es: 'Ingeniero en Energías Renovables por la UNAM, con 5 años de experiencia laboral en proyectos solares GD en México. Con +25 MWp instalados en +100 instalaciones trabajando con clientes como Prologis, Chedraui, Casa Ley, Coppel, etc. Actualmente Director de Construcción en Energía Real siendo responsable de los todos proyectos solares y BESS.',
        resume_en: 'Renewable Energy Engineer by UNAM, with 5 years of work experience in solar DG projects in Mexico. With +25 MWp installed in +100 installations working with clients such as Prologis, Chedraui, Casa Ley, Coppel, etc. Currently Director of Construction at Energía Real being responsible for all solar and BESS projects.',
    },
    {
        id:2,
        name: 'Gustavo Marín',
        avatar: '/speakers/gustavo_marin.webp',
        role_es: "Branch Manager en LATAM APsystems - Altenergy Power Systems",
        role_en: "Branch Manager en LATAM APsystems - Altenergy Power Systems",
        resume_es: 'Cuenta con una Ingeniería en Comunicación Electrónica por parte de la UdeG en el Centro de Ciencias Exactas e Ingeniería de la ciudad de Guadalajara, Jalisco, México. Tiene una maestría en Tecnología Ambiental por parte de UTEL y una amplia experiencia en la energía solar desde el 2008. Sus inicios fueron en empresas de manufactura como Flextronics realizando Asset Management. Actualmente, lleva 8 años en APsystems como Branch Manager. Con experiencia en más de 200 entrenamientos virtuales, ha dado entrenamientos en Colombia, Brasil, Guatemala, Honduras, República Dominicana, Panamá, Cuba y México para la industria, profesionalizando al sector sobre las tecnologías de Altenergy Power Systems e impulsando las buenas prácticas. Presentó ante maestros y doctores especializados en eléctrica en Cuba una plática y asesoría acerca de la tecnología en microinversores. Estuvo en Flextronics en cotizaciones Asset Management y también estuvo en el rubro de telecomunicaciones.',
        resume_en: 'He has a degree in Electronic Communication Engineering from the UdeG at the Center for Exact Sciences and Engineering in Guadalajara, Jalisco, Mexico. He has a master\'s degree in Environmental Technology from UTEL and extensive experience in solar energy since 2008. His beginnings were in manufacturing companies such as Flextronics performing Asset Management. Currently, he has been with APsystems for 8 years as Branch Manager. With experience in more than 200 virtual trainings, he has given trainings in Colombia, Brazil, Guatemala, Honduras, Dominican Republic, Panama, Cuba and Mexico for the industry, professionalizing the sector on Altenergy Power Systems technologies and promoting best practices. Presented a lecture and advice on microinverter technology to teachers and doctors specialized in electricity in Cuba. He was in Flextronics in Asset Management quotations and was also in the telecommunications area.'
    },
    {
        id:3,
        name: 'Juan Carlos Fuentes',
        avatar: '/speakers/juan_carlos_fuentes.webp',
        role_es: "Director de Ventas para Latinoamérica & Europa, en S-5!",
        role_en: "Director of Sales for Latin America & Europe, at S-5!",
        resume_es: 'Arquitecto con residencia en EE. UU., cuenta con más de 15 años de experiencia en el desarrollo de mercados internacionales en el sector de materiales de construcción para empresas europeas y americanas. Actualmente, en S-5! dirige iniciativas estratégicas de planificación de ventas, capacitación y desarrollo del equipo de LATAN & Europa; al mismo tiempo, que construye fuertes relaciones con los partners de S-5!',
        resume_en: 'A U.S.-based architect, he has over 15 years of experience in international market development in the building materials sector for European and American companies. Currently, at S-5! he leads strategic initiatives in sales planning, training and development of the LATAN & Europe team, while building strong relationships with S-5! partners.'
    },
    {
        id:4,
        name: 'José Adolfo Ortiz Martínez',
        avatar: '/speakers/jose_adolfo.webp',
        role_es: "",
        role_en: "",
        resume_es: "Información por confirmar",
        resume_en: "Information to be confirmed",
    },
    {
        id:5,
        name: 'Iván Zavala Vera',
        avatar: '/speakers/ivan_zavala_vera.webp',
        role_es: "",
        role_en: "",
        resume_es: "Información por confirmar",
        resume_en: "Information to be confirmed",
    },
    {
        id:6,
        name: 'Raul Romay',
        avatar: '/speakers/raul_romay.webp',
        role_es: "",
        role_en: "",
        resume_es: 'Energía solar al alcance de tus manos: Herramientas Financieras para proyectos Fotovoltaicos, ademas de explorar el futuro de la energía con sistemas de lmacenamiento en México',
        resume_en: 'Solar energy at your fingertips: Financial tools for photovoltaic projects, as well as exploring the future of energy with storage systems in México.'
    },
    {
        id:7,
        name: 'Mayela Cifuentes',
        avatar: '/speakers/mayela_cinfuentes.webp',
        role_es: "",
        role_en: "",
        resume_es: "Información por confirmar",
        resume_en: "Information to be confirmed",
    },
    {
        id:8,
        name: 'Javier López',
        avatar: '/speakers/javier_lopez.webp',
        role_es: "",
        role_en: "",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id:9,
        name: 'Erick Möller',
        avatar: '/speakers/erick-moller.webp',
        role_es: "Gerente Regional Ventas LATAM, en Slots Exel Solar",
        role_en: "Regional Sales Manager LATAM, at Slots Exel Solar",
        resume_es: "Licenciado en Ingeniería en Desarrollo Sostenible por el Tecnológico de Monterrey. Es apasiado por la sostenibilidad y el bienestar social. Su compromiso con proyectos de Energía Renovable, Desarrollo Urbano Consciente y Emprendimiento Social lo han destacado como un líder visionario. Actualmente, es Gerente Regional de Ventas de Sol-Ark Latinoamérica. Asimismo, continúa impulsando soluciones innovadoras para un futuro más sostenible y prometedor.",
        resume_en: "He holds a degree in Sustainable Development Engineering from Tecnológico de Monterrey. He is passionate about sustainability and social welfare. His commitment to Renewable Energy, Conscious Urban Development and Social Entrepreneurship projects has made him stand out as a visionary leader. Currently, he is Regional Sales Manager for Sol-Ark Latin America. He also continues to promote innovative solutions for a more sustainable and promising future.",
    },
    {
        id:10,
        name: 'David Gutiérrez',
        avatar: '/speakers/david-gutierrez.webp',
        role_es: "Country Manager México, de Victron Energy",
        role_en: "Country Manager Mexico, Victron Energy",
        resume_es: "Ingeniero en Energía, especialista en Sistemas de Almacenamiento de Energía. Encargado del mercado mexicano para la empresa Victron Energy, ha trabajado en la industria fotovoltaica desde el 2012 desarrollando proyectos fotovoltaicos. Desde 2019 se ha dedicado a la capacitación de profesionales, integradores y empresarios sobre las aplicaciones del almacenamiento de energía. Asimismo, ha participado en el diseño e implementación exitosa de sistemas fotovoltaicos con baterías en todo México.",
        resume_en: "Energy Engineer, specialist in Energy Storage Systems. In charge of the Mexican market for Victron Energy, he has worked in the photovoltaic industry since 2012 developing photovoltaic projects. Since 2019 he has been dedicated to training professionals, integrators and entrepreneurs on energy storage applications. He has also participated in the design and successful implementation of PV systems with batteries throughout Mexico.",
    },
    {
        id:11,
        name: 'Alejandro Fajer Botaya',
        avatar: '/speakers/alejandro-fajer.webp',
        role_es: "COO de Quartux México",
        role_en: "COO de Quartux México",
        resume_es: "Especialista en el sector energético. Actualmente, funge como Director de Operaciones en Quartux, una empresa mexicana que ofrece soluciones de almacenamiento de energía que utiliza tecnología ion-litio. Además, ha colaborado como consultor en energía en Endeavor México en el área de emprendimiento, así como en el banco Morgan Stanley en el área de Energía. Es egresado de la Universidad Iberoamericana como Ingeniero Químico y cuenta con diplomado en Filosofía Moderna. Además, ha realizado cursos de doctorado enTecnología de Sistemas de Almacenamiento, en el Swiss Federal Institute of Technology (ETH Zurich) y de Gestión Estratégica, en la Universidad de Harvard.",
        resume_en: "Specialist in the energy sector. He currently serves as Director of Operations at Quartux, a Mexican company that offers energy storage solutions using lithium-ion technology. In addition, he has collaborated as an energy consultant at Endeavor Mexico in the area of entrepreneurship, as well as at Morgan Stanley Bank in the area of Energy. He has a degree in Chemical Engineering from the Universidad Iberoamericana and a diploma in Modern Philosophy. He has also completed doctoral courses in Storage Systems Technology at the Swiss Federal Institute of Technology (ETH Zurich) and in Strategic Management at Harvard University.",
    },
    {
        id: 12,
        name: 'Daniel Fuchs',
        avatar: '/speakers/daniel-fuchs.webp',
        role_es: "Director de Atención al Cliente (CCO), International Battery & Energy Storage Alliance - IBESA",
        role_en: "Chief Customer Officer (CCO), International Battery & Energy Storage Alliance - IBESA",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 13,
        name: 'Marcel Gómez Pecina',
        avatar: '/speakers/marcel-gomez.webp',
        role_es: "Desarrollador de negocios energéticos, en ON. Energy",
        role_en: "Energy Business Developer, ON. Energy",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 14,
        name: 'Erika Ramírez',
        avatar: '/speakers/erika-ramirez.webp',
        role_es: "Analista Senior de Operaciones, en Acclaim Energy México",
        role_en: "Senior Operations Analyst, Acclaim Energy Mexico",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 15,
        name: 'Carlos Torres Almazán',
        avatar: '/speakers/carlos-torres.webp',
        role_es: " Director General, de EMS Latinomérica",
        role_en: "General Manager, EMS Latin America",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 16,
        name: 'Maximiliano Orduño',
        avatar: '/speakers/maximiliano-orduno.webp',
        role_es: "Especialista de Producto, en Growatt",
        role_en: "Product Specialist, Growatt",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 17,
        name: 'Santiago Torres',
        avatar: '/speakers/santiago-torres.webp',
        role_es: "Socio Director de Pireos Power",
        role_en: "Managing Partner of Pireos Power",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 18,
        name: 'Abdiel Portillo',
        avatar: '/speakers/abdiel-portillo.webp',
        role_es: "Asesor Técnico Comercial, de Fronius Mexico",
        role_en: "Technical Sales Advisor, Fronius Mexico",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 19,
        name: 'Marco V. Calderón Agoitia',
        avatar: '/speakers/marco-v-calderon.webp',
        role_es: "Socio Director de Cosmo Consulting",
        role_en: "Managing Partner of Cosmo Consulting",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 20,
        name: "Patricia Tattó",
        avatar: '/speakers/patricia-tatto.webp',
        role_es: "Asesora en VP Ata Renewables America",
        role_en: "Advisor at VP Ata Renewables America",
        resume_es: "Licenciada en derecho por la Universidad Iberoamericana, con estudios en Derechos Humanos, por la Universidad Birbeck, en Reino Unido. ha dedicado su carrera a desarrollar e impulsar la industria de Energía Renovable en los mercados energéticos internacionales, como asesora técnica y guía de negocios en la creación de estrategias para la industria en nuevos mercados.En VP Ata Renewables America, asesora a toda la cadena de valor sobre la implementación exitosa de proyectos de energía renovable a gran escala. Fundó y es la actual presidenta de Mujeres en Energía Renovable Mexico AC, una organización sin fines de lucro en todo el sector de las energías renovables, con el propósito de empoderar a las mujeres en el campo de la energía renovable en LATAM.",
        resume_en: "With a law degree from the Universidad Iberoamericana, with studies in Human Rights from Birbeck University in the United Kingdom, she has dedicated her career to developing and promoting the Renewable Energy industry in international energy markets, as a technical advisor and business guide in the creation of strategies for the industry in new markets. At VP Ata Renewables America, she advises the entire value chain on the successful implementation of large-scale renewable energy projects. She founded and is the current president of Mujeres en Energía Renovable Mexico AC, a non-profit organization in the entire renewable energy sector, with the purpose of empowering women in the field of renewable energy in LATAM.",
    },
    {
        id: 21,
        name: 'César Garma',
        avatar: '/speakers/cesar-garma.webp',
        role_es: "Director de Estrategia de Transición Energética, en Saving With Energy México",
        role_en: "Director of Energy Transition Strategy, Saving With Energy Mexico",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 22,
        name: 'Héctor Núñez',
        avatar: '/speakers/hector-nunez.webp',
        role_es: "Jefe de Ventas para Norteamérica en Sungrow Power Supply",
        role_en: "Head of Sales North America at Sungrow Power Supply",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 23,
        name: 'Luis Antonio Hernández García',
        avatar: '/speakers/luis-hernandez.webp',
        role_es: "Director General en Battery DepotMx",
        role_en: "Director General en Depósito de BateríasMx",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 24,
        name: 'Rogelio Nochebuena',
        avatar: '/speakers/rogelio-nochebuena.webp',
        role_es: "Director de SEBA - Servicios Ambientales de Baja California",
        role_en: "Director of SEBA - Environmental Services of Baja California",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 25,
        name: 'Monica Huang',
        avatar: '/speakers/speakers_ssm_eco.png',
        role_es: "Directora Regional de Ventas para América, ATESS POWER TECHNOLOGY",
        role_en: "Regional Sales Director Americas, ATESS POWER TECHNOLOGY",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 26,
        name: 'Billy Martínez',
        avatar: '/speakers/billy-martinez.webp',
        role_es: "",
        role_en: "",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 27,
        name: 'Karen Lugo',
        avatar: '/speakers/karen-lugo.webp',
        role_es: "Departamento de ingeniería, Battery Depot",
        role_en: "Engineering Department, Battery Depot",
        resume_es: "Ingeniera en Energías Renovables, por el Instituto Tecnológico Superior de Huichapan. Profesional altamente calificada en el sector de las Energías Renovables, con una experiencia de 6 años en la industria. Su destreza en el diseño de Sistemas de Almacenamiento de Energía en Baterías (BESS) de alto y bajo voltaje, junto con su enfoque proactivo de brindar asesorías personalizadas para resolver problemas de manera efectiva, la destacan en su rol en el departamento de ingeniería de Battery Depot, empresa en la que trabaja actualmente.",
        resume_en: "Engineer in Renewable Energies, by the Instituto Tecnológico Superior de Huichapan. Highly qualified professional in the Renewable Energy sector, with 6 years of experience in the industry. Her skills in the design of high and low voltage Battery Energy Storage Systems (BESS), together with her proactive approach to providing personalised advice to solve problems effectively, make her stand out in her role in the engineering department of Battery Depot, the company where she currently works.",
    },
    {
        id: 28,
        name: 'Abel Villa',
        avatar: '/speakers/abel-villa.webp',
        role_es: "Ingeniero Líder, en Battery Depot",
        role_en: "Lead Engineer, Battery Depot",
        resume_es: "Egresado de la Universidad de Guadalajara del Centro Universitario de Tonalá de la carrera de Ingeniería en Energía. Con experiencia en el sector energético y con conocimiento técnico en equipos para sistemas fotovoltaicos. Su pasión por la innovación y la sostenibilidad lo ha llevado a especializarse en la conversión de vehículos de combustión a eléctricos. Está comprometido con la creación de un futuro más limpio y sostenible a través de la electrificación del transporte, por lo que está dedicado a impulsar esta transformación a través de su trabajo y su liderazgo en la industria. Destaca como un Ingeniero Líder en este campo dentro de la empresa Battery Depot, trabajando incansablemente para impulsar el cambio hacia un futuro más limpio y sostenible en la industria automotriz.",
        resume_en: "Graduated from the University of Guadalajara, Centro Universitario de Tonalá, with a degree in Energy Engineering.With experience in the energy sector and technical knowledge in equipment for photovoltaic systems.His passion for innovation and sustainability has led him to specialise in the conversion of vehicles from combustion to electric. He is committed to creating a cleaner, more sustainable future through the electrification of transport and is dedicated to driving this transformation through his work and leadership in the industry. He stands out as a Lead Engineer in this field within Battery Depot, working tirelessly to drive change towards a cleaner, more sustainable future in the automotive industry.",
    },
    {
        id: 29,
        name: 'Aideé Zamora',
        avatar: '/speakers/aidee-zamora.webp',
        role_es: "Coordinadora General REDMEREE",
        role_en: "General Coordinator REDMEREE",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 30,
        name: 'David Aguirre',
        avatar: '/speakers/david-aguirre.webp',
        role_es: "Responsable de sistemas de almacenamiento, en BayWa R.E. México",
        role_en: "Storage Systems Manager, at BayWa R.E. México",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 31,
        name: 'Erick de la Rosa',
        avatar: '/speakers/erick-rosa.webp',
        role_es: "Gerente de Ventas para LATAM, en S-5!",
        role_en: "LATAM Sales Manager",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 32,
        name: 'Isabel Bazán',
        avatar: '/speakers/isabel-bazan.webp',
        role_es: "Coordinadora de Empleabilidad REDMEREE",
        role_en: "Employability Coordinator REDMEREE",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 33,
        name: 'Kennia Espinoza',
        avatar: '/speakers/kennia-espinoza.webp',
        role_es: "Directora de Ventas de la DG México",
        role_en: "Sales Director DG Mexico",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 34,
        name: 'Salvador Barba',
        avatar: '/speakers/salvador-barba.webp',
        role_es: "Gerente de Ventas para LATAM, en S-5!",
        role_en: "LATAM Sales Manager",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    {
        id: 35,
        name: "Casiopea Ramírez Melgar",
        avatar: '/speakers/casiopea_ramirez.webp',
        role_es: "Socia de Fresh Energy Consulting",
        role_en: "Partner of Fresh Energy Consulting",
        resume_es: "Fundadora de Voz Experta, internacionalista y maestra en geopolítica, y se ha especializado en Regulación de Utilities, por el Public Utility Research Center, de la Universidad de Florida. Experta en regulación y análisis de mercado con 20 años de experiencia en proyectos de transición energética. A lo largo de su trayectoria, ha colaborado con empresas multinacionales de energía, así como consultoras dedicadas a proyectos de mitigación y adaptación al cambio climático en México, Centro América y el Sudeste Asiático. Actualmente, es socia de Fresh Energy Consulting, donde lidera los análisis de impacto regulatorio, estudios de inteligencia de mercado y diseño de estrategias de comercialización; además, participa como perita experta en procesos legales del sector electricidad a nivel internacional. Funge como Presidenta y Consejera Fundadora de Voz Experta, iniciativa dedicada a visibilizar expertas en el sector energía.",
        resume_en: "Founder of Voz Experta, internationalist and master in Geopolitics, and has specialized in Utilities Regulation, by the Public Utility Research Center, University of Florida. She is an expert in regulation and market analysis with 20 years of experience in energy transition projects. Throughout her career, she has collaborated with multinational energy companies, as well as consulting firms dedicated to climate change mitigation and adaptation projects in Mexico, Central America and Southeast Asia. Currently, she is a partner at Fresh Energy Consulting, where she leads regulatory impact analysis, market intelligence studies and marketing strategy design; in addition, she participates as an expert in legal processes in the electricity sector at an international level. She serves as President and Founding Advisor of Voz Experta, an initiative dedicated to making women experts in the energy sector visible.",
    },
    {
        id:36,
        name: "Gilberto Sánchez Nogueira",
        avatar: '/speakers/gilberto_sanchez.webp',
        role_es: "Secretario Legislativo en la Asociación Nacional de Energía Solar",
        role_en: "National Solar Energy Association Legislative Secretary",
        resume_es: "Con una sólida experiencia de más de 12 años en el sector de Generación Distribuida, ha desempeñado diversos roles clave. Desde asesorar en regulación del sector eléctrico hasta colaborar en programas de mejora en el sector fotovoltaico, su contribución ha sido notable. Además, ha participado en la formulación de políticas energéticas, como en el Programa Especial de Transición Energética, de la SENER en 2016. Su compromiso con el avance del sector se refleja en su participación en foros nacionales e internacionales y en su labor como Secretario Legislativo en la Asociación Nacional de Energía Solar. Certificado por el Consejo de Profesionales de la Energía Fotovoltaica, su experiencia y dedicación son invaluables en el impulso hacia un futuro más sostenible en energía.",
        resume_en: "With a solid experience of more than 12 years in the Distributed Generation sector, he has played several key roles. From advising on electricity sector regulation to collaborating in improvement programs in the photovoltaic sector, his contribution has been remarkable. In addition, he has participated in the formulation of energy policies, such as in the Special Energy Transition Program, by SENER in 2016. His commitment to the advancement of the sector is reflected in his participation in national and international forums and in his work as Legislative Secretary in the National Solar Energy Association. Certified by the Council of Photovoltaic Professionals, his experience and dedication are invaluable in the drive towards a more sustainable energy future.",
    },
    {
        id: 37,
        name: 'Alba Min Ye',
        avatar: '/speakers/alba-min-ye.webp',
        role_es: "Directora General de la región MCC de LONGi",
        role_en: "General Manager MCC region for LONGi",
        resume_es: "La información se está actualizando. Por favor, mantente atento.",
        resume_en: "Information is being updated. Please stay tuned.",
    },
    // {
    //     id: 0,
    //     name: '',
    //     avatar: '',
    //     role_es: "",
    //     role_en: "",
    //     resume_es: "",
    //     resume_en: "",
    // },
]

export { speakers, speakersEdu }
  